apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopno-data

resources:
- migrate-job.yaml

configMapGenerator:
- name: postgres-platform-migrations
  files:
  - 012-payment-schema-reconciliation.sql
  options:
    disableNameSuffixHash: true

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/part-of: shopnoltd
