APP_NAME=ShopNoLtd
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=https://shopnoltd.onrender.com

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=db
DB_PORT=5432
DB_DATABASE=shopnoltd_db
DB_USERNAME=shopnouser
DB_PASSWORD=Asad18081978#

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=shopnoltd@example.com
MAIL_FROM_NAME="${APP_NAME}"
