apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-service-data
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  namespace: shopno-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: shopnoltd-local-immediate
  resources:
    requests:
      storage: 10Gi
