apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-service-data
  namespace: shopno-identity
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
