apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc
  namespace: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc
  template:
    metadata:
      labels:
        app: kc
    spec:
      containers:
      - name: kc
        image: localhost:5000/shopnoltd-kpi:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgis://kobo:kobo_pass@postgres.toolbox.svc.cluster.local:5432/kpidb
        - name: KPI_DATABASE_URL
          value: postgis://kobo:kobo_pass@postgres.toolbox.svc.cluster.local:5432/kpidb
        - name: KC_DATABASE_URL
          value: postgis://kobo:kobo_pass@postgres.toolbox.svc.cluster.local:5432/kobodb
        - name: MONGO_DB_URL
          value: mongodb://mongo.toolbox.svc.cluster.local:27017/kobocat
        - name: REDIS_SESSION_URL
          value: redis://redis.toolbox.svc.cluster.local:6379/1
        - name: REDIS_CACHE_URL
          value: redis://redis.toolbox.svc.cluster.local:6379/2
        - name: CACHE_URL
          value: redis://redis.toolbox.svc.cluster.local:6379/2
        - name: DJANGO_SETTINGS_MODULE
          value: kobo.settings.prod
        - name: DJANGO_SECRET_KEY
          value: y42k8K4M-Ixcc0cGE-f7uLFNMGjrpVs9FK3iQje5UkmdGkWamW9k8Wlx0eoHNaSEQd0
        - name: KPI_PREFIX
          value: /
        - name: PUBLIC_DOMAIN_NAME
          value: shopnoltd.dpdns.org
        - name: KOBOFORM_URL
          value: https://kobo.shopnoltd.dpdns.org
        - name: KOBOCAT_URL
          value: https://kf.shopnoltd.dpdns.org
        - name: SECURE_PROXY_SSL_HEADER
          value: HTTP_X_FORWARDED_PROTO, https
        - name: USE_X_FORWARDED_HOST
          value: "true"
        - name: PUBLIC_REQUEST_SCHEME
          value: https
        volumeMounts:
        - name: kc-media
          mountPath: /srv/src/kpi/media
        - name: kf-media
          mountPath: /srv/src/kobocat/media
        - name: kf-init-scripts
          mountPath: /srv/init
        - name: uwsgi-ini-override          # <-- NEW
          mountPath: /srv/src/kpi/docker/uwsgi.ini   # <-- NEW
          subPath: uwsgi.ini                 # <-- NEW
      volumes:
      - name: kc-media
        persistentVolumeClaim:
          claimName: kc-media-pvc
      - name: kf-media
        persistentVolumeClaim:
          claimName: kf-media-pvc
      - name: kf-init-scripts
        configMap:
          name: kf-init-scripts
          defaultMode: 0755
      - name: uwsgi-ini-override             # <-- NEW
        configMap:                            # <-- NEW
          name: kc-uwsgi-ini                  # <-- NEW
---
apiVersion: v1
kind: Service
metadata:
  name: kc
  namespace: toolbox
spec:
  selector:
    app: kc
  ports:
  - name: http
    port: 80
    targetPort: 8000