import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Database, Download, FileUp, Lock, RefreshCw, Save, ShieldCheck, Trash2, Upload, X } from 'lucide-react'

const PAGE_SIZE = 50
const API = ''
const SERVICES = [
  ['payment-service', 'Financial PostgreSQL', 'protected'],
  ['billing-engine', 'Billing PostgreSQL', 'protected'],
  ['exchange-service', 'Exchange PostgreSQL', 'protected'],
  ['auth-service / Keycloak', 'Identity store', 'protected'],
  ['domain-service', 'Domain PostgreSQL', 'controlled'],
  ['freedomain-service', 'Tenant/domain PostgreSQL', 'controlled'],
  ['ai-platform', 'AI PostgreSQL', 'controlled'],
  ['social/blog', 'Content PostgreSQL', 'crud'],
  ['analytics-service', 'Analytics store', 'controlled'],
  ['KoboToolbox / KoBoCat / Enketo', 'Application stores', 'application'],
  ['mail / meeting / storage', 'Application metadata', 'application'],
  ['audit-service', 'Append-only audit store', 'readonly'],
]
const MODES = [['add', 'Add'], ['update', 'Update'], ['upsert', 'Upsert'], ['merge', 'Merge'], ['delete', 'Delete'], ['replace_rows', 'Replace rows']]

function headers(extra = {}) { const t = localStorage.getItem('shopno_token'); return { Accept: 'application/json', ...(t ? { Authorization: `Bearer ${t}` } : {}), ...extra } }
async function api(path, options = {}) { const r = await fetch(`${API}${path}`, { ...options, headers: headers(options.headers || {}) }); const text = await r.text(); let data = null; try { data = text ? JSON.parse(text) : null } catch { data = text }; if (!r.ok) throw new Error(data?.detail || data?.message || text || `HTTP ${r.status}`); return data }
function downloadBlob(blob, filename) { const u = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = u; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(u), 0) }

export default function DatabaseControlPlaneEnhanced() {
  const [service, setService] = useState('social/blog'), [tables, setTables] = useState([]), [table, setTable] = useState('')
  const [rows, setRows] = useState([]), [analysis, setAnalysis] = useState(null), [query, setQuery] = useState('')
  const [mode, setMode] = useState('add'), [file, setFile] = useState(null), [preview, setPreview] = useState(null)
  const [editor, setEditor] = useState(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const current = useMemo(() => SERVICES.find(x => x[0] === service) || SERVICES[0], [service])
  const blog = service === 'social/blog', payment = service === 'payment-service'

  useEffect(() => { reset(); if (blog) inspectBlog(); if (payment) inspectPayment() }, [service])
  function reset() { setTables([]); setTable(''); setRows([]); setAnalysis(null); setFile(null); setPreview(null); setEditor(null); setMessage('') }

  async function inspectPayment() { setBusy(true); try { const d = await api('/api/v1/admin/tables'); setTables(Array.isArray(d) ? d : []); if (d?.[0]?.name) await inspectPaymentTable(d[0].name) } catch (e) { setMessage(`Database inspection failed: ${e.message}`) } finally { setBusy(false) } }
  async function inspectPaymentTable(name = table) { if (!name) return; setBusy(true); setTable(name); try { const q = new URLSearchParams({ limit: PAGE_SIZE, offset: 0 }); if (query) q.set('search', query); const d = await api(`/api/v1/admin/tables/${encodeURIComponent(name)}?${q}`); setRows(d?.rows || []); setAnalysis(await api(`/api/v1/admin/tables/${encodeURIComponent(name)}/analysis`)) } catch (e) { setMessage(`Entity inspection failed: ${e.message}`) } finally { setBusy(false) } }
  async function inspectBlog() { setBusy(true); try { const [a, r] = await Promise.all([api('/api/v1/admin/blog-data/analysis'), api('/api/v2/blog/admin')]); setAnalysis(a); setRows(Array.isArray(r) ? r : (r?.items || [])) } catch (e) { setMessage(`Blog inspection failed: ${e.message}`) } finally { setBusy(false) } }

  async function exportData(format) { setBusy(true); try { const path = blog ? `/api/v1/admin/blog-data/export?format=${format}` : `/api/v1/admin/tables/${encodeURIComponent(table)}/export?format=${format}`; const r = await fetch(path, { headers: headers() }); if (!r.ok) throw new Error(`HTTP ${r.status}`); downloadBlob(await r.blob(), `${blog ? 'blog_posts' : table}.${format}`) } catch (e) { setMessage(`Export failed: ${e.message}`) } finally { setBusy(false) } }
  async function report() { if (!table) return; setBusy(true); try { const r = await fetch(`/api/v1/admin/data-reports/${encodeURIComponent(table)}/pdf`, { headers: headers() }); if (!r.ok) throw new Error(`HTTP ${r.status}`); downloadBlob(await r.blob(), `${table}.pdf`) } catch (e) { setMessage(`Report failed: ${e.message}`) } finally { setBusy(false) } }

  async function previewImport(e) { const f = e.target.files?.[0]; setFile(f || null); setPreview(null); if (!f || !blog) return; setBusy(true); try { const form = new FormData(); form.append('file', f); setPreview(await api(`/api/v1/admin/blog-data/import/preview?operation=${encodeURIComponent(mode)}`, { method: 'POST', body: form })) } catch (x) { setMessage(`Import validation failed: ${x.message}`) } finally { setBusy(false) } }
  async function commitImport() { if (!file || !preview || !blog) return; if (mode === 'delete' || mode === 'replace_rows') { if (!window.confirm(`Confirm destructive ${mode} operation?`)) return } setBusy(true); try { const form = new FormData(); form.append('file', file); const suffix = mode === 'delete' || mode === 'replace_rows' ? '&confirm=true' : ''; const r = await api(`/api/v1/admin/blog-data/import?operation=${encodeURIComponent(mode)}${suffix}`, { method: 'POST', body: form }); setMessage(`Import committed: ${JSON.stringify(r)}`); setFile(null); setPreview(null); await inspectBlog() } catch (e) { setMessage(`Import failed and was rolled back: ${e.message}`) } finally { setBusy(false) } }

  function newBlog() { setMode('add'); setEditor({ title: '', slug: '', excerpt: '', content: '', cover_image: '', status: 'draft' }) }
  function editBlog(row) { setMode('update'); setEditor({ id: row.id, title: row.title || '', slug: row.slug || '', excerpt: row.excerpt || '', content: row.content || '', cover_image: row.cover_image || '', status: row.status || 'draft' }) }
  async function saveBlog() { if (!editor) return; setBusy(true); try { const id = editor.id; const payload = { title: editor.title, slug: editor.slug, excerpt: editor.excerpt, content: editor.content, cover_image: editor.cover_image, status: editor.status }; const r = id ? await api(`/api/v1/admin/blog-data/rows/${encodeURIComponent(id)}`, { method: 'PUT', body: JSON.stringify(payload) }) : await api('/api/v1/admin/blog-data/rows', { method: 'POST', body: JSON.stringify(payload) }); setEditor(null); setMessage(`${id ? 'Updated' : 'Added'} blog row ${r.id}`); await inspectBlog() } catch (e) { setMessage(`Save failed: ${e.message}`) } finally { setBusy(false) } }
  async function publishBlog(row, published = true) { setBusy(true); try { await api(`/api/v1/admin/blog-data/rows/${encodeURIComponent(row.id)}/publish?published=${published}`, { method: 'POST' }); await inspectBlog() } catch (e) { setMessage(`Publish operation failed: ${e.message}`) } finally { setBusy(false) } }
  async function deleteBlog(row) { if (!window.confirm(`Delete “${row.title}”? This is permanent; the audit entry remains.`)) return; setBusy(true); try { await api(`/api/v1/admin/blog-data/rows/${encodeURIComponent(row.id)}?confirm=true`, { method: 'DELETE' }); await inspectBlog() } catch (e) { setMessage(`Delete failed: ${e.message}`) } finally { setBusy(false) } }

  const numericValues = analysis ? [analysis.rows || 0, analysis.columns || 0, analysis.status_distribution?.draft || 0, analysis.status_distribution?.published || 0] : []
  const maxMetric = Math.max(1, ...numericValues)
  return <main style={styles.page}><div style={styles.wrap}>
    <header><div style={styles.title}><Database size={26}/><h1>Database Control Plane</h1></div><p style={styles.muted}>Service-owned data control with guarded CRUD, import/export, analysis, reporting and audit-safe boundaries. No browser-side SQL or unrestricted financial mutation.</p></header>
    <section style={styles.metrics}><Metric icon={<Database size={17}/>} label="Data domains" value={SERVICES.length}/><Metric icon={<ShieldCheck size={17}/>} label="Protected boundaries" value={SERVICES.filter(x => x[2] !== 'crud').length}/><Metric icon={<Lock size={17}/>} label="Generic financial writes" value="0"/><Metric icon={<BarChart3 size={17}/>} label="HD / 4K-ready charts" value="SVG"/></section>
    {message && <div role="status" style={styles.notice}>{message}<button onClick={() => setMessage('')} style={styles.close}><X size={14}/></button></div>}
    <div style={styles.layout}><aside style={styles.panel}><strong>Services / stores</strong>{SERVICES.map(x => <button key={x[0]} onClick={() => setService(x[0])} style={{...styles.nav, ...(service === x[0] ? styles.active : {})}}>{x[0]}<small>{x[1]} · {x[2]}</small></button>)}</aside>
      <section style={{display:'grid',gap:14}}><section style={styles.panel}><div style={styles.between}><div><h2 style={{margin:0}}>{current[0]}</h2><div style={styles.muted}>{current[1]}</div></div><span style={styles.badge}>{current[2]}</span></div>
        {blog && <div style={styles.toolbar}><button onClick={newBlog} style={styles.action}><Save size={14}/> Add row</button>{MODES.map(([v,l]) => <button key={v} onClick={() => setMode(v)} style={{...styles.small,...(mode===v?styles.selected:{})}}>{l}</button>)}<label style={styles.small}><Upload size={13}/> Import<input type="file" accept=".csv,.json,.xlsx" onChange={previewImport} hidden/></label>{['json','csv','xlsx','pdf'].map(f => <button key={f} onClick={() => exportData(f)} style={styles.small}><Download size={13}/>{f.toUpperCase()}</button>)}</div>}
        {payment && <div style={styles.toolbar}><button onClick={inspectPayment} disabled={busy} style={styles.action}><RefreshCw size={14}/> Inspect live DB</button>{table && <><button onClick={() => exportData('json')} style={styles.small}>JSON</button><button onClick={() => exportData('csv')} style={styles.small}>CSV</button><button onClick={() => exportData('xlsx')} style={styles.small}>XLSX</button><button onClick={report} style={styles.small}>PDF report</button></>}</div>}
      </section>
      {blog && editor && <section style={styles.panel}><div style={styles.between}><h3 style={{margin:0}}>{editor.id ? 'Edit blog row' : 'Add blog row'}</h3><button onClick={() => setEditor(null)} style={styles.small}><X size={13}/>Cancel</button></div><div style={styles.formGrid}>{[['title','Title'],['slug','Slug'],['excerpt','Excerpt'],['cover_image','Cover image URL']].map(([k,l]) => <label key={k}>{l}<input value={editor[k]} onChange={e=>setEditor({...editor,[k]:e.target.value})} style={styles.input}/></label>)}<label style={{gridColumn:'1/-1'}}>Content<textarea rows={10} value={editor.content} onChange={e=>setEditor({...editor,content:e.target.value})} style={styles.input}/></label><label>Status<select value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})} style={styles.input}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><button onClick={saveBlog} disabled={busy} style={styles.action}><Save size={14}/> Save transaction</button></section>}
      {blog && preview && <section style={styles.panel}><div style={styles.between}><h3 style={{margin:0}}>Validated import preview</h3><button onClick={commitImport} disabled={busy||!file} style={styles.action}>Commit import</button></div><pre style={styles.pre}>{JSON.stringify(preview,null,2)}</pre></section>}
      {payment && tables.length>0 && <section style={styles.panel}><h3 style={{marginTop:0}}>Live entity inventory</h3><div style={styles.scroll}><table style={styles.table}><thead><tr><th>Entity</th><th>Write</th><th>Columns</th><th>Sensitive</th></tr></thead><tbody>{tables.map(x=><tr key={x.name} onClick={()=>inspectPaymentTable(x.name)}><td>{x.name}</td><td>{x.writable?'Controlled':'No'}</td><td>{x.columns?.length??'—'}</td><td>{x.financially_sensitive?'Protected':'Policy'}</td></tr>)}</tbody></table></div>{table&&<div style={styles.row}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search current entity…" style={styles.input}/><button onClick={()=>inspectPaymentTable()} style={styles.action}>Search</button></div>}</section>}
      {analysis && <section style={styles.panel}><div style={styles.between}><div><h3 style={{margin:0}}>Analysis & reporting</h3><div style={styles.muted}>Resolution-independent SVG scales cleanly for HD/4K displays.</div></div>{table&&<button onClick={report} style={styles.small}>Generate PDF report</button>}</div><div style={styles.chart3d}>{numericValues.map((v,i)=><div key={i} style={{...styles.bar3d,height:`${Math.max(8,(v/maxMetric)*150)}px`}} title={String(v)}><span>{v}</span></div>)}</div><pre style={styles.pre}>{JSON.stringify(analysis,null,2)}</pre></section>}
      {blog && <section style={styles.panel}><h3 style={{marginTop:0}}>Blog records</h3><div style={styles.scroll}><table style={styles.table}><thead><tr><th>Title</th><th>Status</th><th>Slug</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.status}</td><td>{r.slug}</td><td><div style={styles.row}><button onClick={()=>editBlog(r)} style={styles.small}>Edit</button><button onClick={()=>publishBlog(r,r.status!=='published')} style={styles.small}>{r.status==='published'?'Unpublish':'Publish'}</button><button onClick={()=>deleteBlog(r)} style={{...styles.small,...styles.danger}}><Trash2 size={13}/>Delete</button></div></td></tr>)}</tbody></table></div></section>}
      {rows.length>0 && !blog && <section style={styles.panel}><h3 style={{marginTop:0}}>Entity preview</h3><div style={styles.scroll}><table style={styles.table}><thead><tr>{Object.keys(rows[0]).slice(0,10).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,20).map((r,i)=><tr key={r.id??i}>{Object.keys(rows[0]).slice(0,10).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></section>}
    </section></div></div></main>
}
function Metric({icon,label,value}){return <div style={styles.metric}><div>{icon}</div><small>{label}</small><strong>{value}</strong></div>}
const styles={page:{minHeight:'calc(100vh - 64px)',background:'#0f1419',color:'#e6edf3',padding:'clamp(14px,3vw,36px)'},wrap:{maxWidth:1600,margin:'0 auto'},title:{display:'flex',alignItems:'center',gap:10},muted:{color:'#9da7b3',marginTop:6},metrics:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginBottom:14},metric:{background:'#151b22',border:'1px solid #27303b',borderRadius:10,padding:14,display:'grid',gap:5},layout:{display:'grid',gridTemplateColumns:'minmax(220px,300px) minmax(0,1fr)',gap:14},panel:{background:'#151b22',border:'1px solid #27303b',borderRadius:10,padding:16},between:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'},nav:{display:'block',width:'100%',textAlign:'left',padding:'9px 10px',marginTop:5,border:0,borderRadius:7,background:'transparent',color:'#d8dee6',cursor:'pointer'},active:{background:'#243244'},badge:{padding:'5px 8px',borderRadius:999,border:'1px solid #3a4655',fontSize:12},toolbar:{display:'flex',gap:7,flexWrap:'wrap',marginTop:12},row:{display:'flex',gap:7,flexWrap:'wrap',alignItems:'center'},action:{display:'inline-flex',alignItems:'center',gap:6,padding:'8px 11px',borderRadius:7,border:'1px solid #3a4655',background:'#1e2935',color:'#fff',cursor:'pointer'},small:{display:'inline-flex',alignItems:'center',gap:5,padding:'6px 9px',borderRadius:7,border:'1px solid #3a4655',background:'#1e2935',color:'#fff',cursor:'pointer',fontSize:12},selected:{borderColor:'#d4a054',background:'#2b251a'},danger:{borderColor:'#8b3a3a'},notice:{position:'relative',padding:10,margin:'10px 0',border:'1px solid #5b4726',background:'#201b13',borderRadius:7,color:'#e5c78d',overflowWrap:'anywhere',paddingRight:36},close:{position:'absolute',right:8,top:8,border:0,background:'transparent',color:'#e5c78d',cursor:'pointer'},formGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,margin:'14px 0'},input:{width:'100%',boxSizing:'border-box',padding:9,marginTop:5,borderRadius:7,border:'1px solid #3a4655',background:'#0b0f14',color:'#fff'},pre:{maxHeight:320,overflow:'auto',background:'#0b0f14',padding:10,borderRadius:7,fontSize:12},scroll:{overflowX:'auto',marginTop:12},table:{width:'100%',borderCollapse:'collapse',fontSize:13},chart3d:{height:180,display:'flex',alignItems:'end',gap:18,padding:'16px 24px',background:'linear-gradient(150deg,#111923,#0b1017)',borderRadius:10,marginTop:12,perspective:500},bar3d:{width:45,minHeight:8,background:'linear-gradient(135deg,#2e6b9e,#16334d)',border:'1px solid #4f83aa',transform:'rotateX(8deg) rotateY(-8deg)',boxShadow:'8px 8px 0 rgba(0,0,0,.25)',display:'flex',alignItems:'start',justifyContent:'center',paddingTop:3,fontSize:11}}
