import React, { useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { getExchangeRate } from '../lib/financialApi'
import { platformApi } from '../lib/platformApi'

const box = { maxWidth: 1100, margin: '0 auto', padding: '28px 16px 80px', fontFamily: 'system-ui, sans-serif' }
const card = { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 14, padding: 18, marginBottom: 14 }
const input = { width: '100%', boxSizing: 'border-box', padding: 10, marginTop: 5, border: '1px solid #cbd5e1', borderRadius: 8 }
const CURRENCIES = ['USD','BDT','EUR','GBP','INR','AUD','CAD','SGD','AED','SAR','JPY','CNY','HKD','MYR','THB','IDR','PKR','NPR','LKR','QAR','KWD','OMR','NZD','CHF','SEK','NOK','DKK','ZAR','TRY','BRL']

function WorkNav() { return <nav style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 20 }}><Link to="/work">Browse</Link><Link to="/create-work">Create Work</Link><Link to="/my-created-work">My Created Work</Link><Link to="/my-active-work">My Active Works</Link><Link to="/my-submission">My Submission</Link><Link to="/work-review">Work Review</Link></nav> }

function Browse() {
  const [works, setWorks] = useState([]); const [loading, setLoading] = useState(true)
  const load = () => platformApi.works('open').then(setWorks).catch(e => alert(e.message)).finally(() => setLoading(false))
  useEffect(load, [])
  async function accept(id) { try { await platformApi.acceptWork(id); load() } catch (e) { alert(e.message) } }
  return <><h1>Work</h1><p style={{ color: '#64748b' }}>Browse published tasks with direct detail links, live task totals, remaining tasks and amounts.</p>{loading && <p>Loading…</p>}{works.map(w => <article key={w.id} style={card}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><h3 style={{ marginTop: 0 }}><Link to={`/work/${w.id}`}>{w.title}</Link></h3><b>{w.reward_amount} {w.currency}</b></div><p>{w.description}</p><p><b>Total amount:</b> {w.total_amount} {w.currency} · <b>Total tasks:</b> {w.total_tasks} · <b>Remaining:</b> {w.remaining_tasks} · <b>Remaining amount:</b> {w.remaining_amount} {w.currency}</p><small>Deadline: {w.deadline ? new Date(w.deadline).toLocaleString() : 'No deadline'} · Stage: {w.status}</small><div style={{ marginTop: 12, display: 'flex', gap: 8 }}><Link to={`/work/${w.id}`}>View work</Link><button onClick={() => accept(w.id)}>Accept work</button></div></article>)}{!loading && works.length === 0 && <div style={card}>No published work is available.</div>}</>
}

function Create() {
  const [currencies, setCurrencies] = useState(CURRENCIES); const [baseUsd, setBaseUsd] = useState(''); const [reward, setReward] = useState(''); const [rate, setRate] = useState(null); const [quoting, setQuoting] = useState(false)
  const [form, setForm] = useState({ title: '', description: '', requirements: '', currency: 'BDT', max_workers: 1, deadline: '' }); const [done, setDone] = useState('')
  useEffect(() => { platformApi.currencies().then(x => x?.currencies?.length && setCurrencies(x.currencies)).catch(() => {}) }, [])
  useEffect(() => { let cancelled = false; const usd = Number(baseUsd); if (!usd || usd <= 0) { setReward(''); setRate(null); return } if (form.currency === 'USD') { setRate(1); setReward(usd.toFixed(2)); return } setQuoting(true); getExchangeRate('USD', form.currency).then(x => { const r = Number(x?.rate); if (!Number.isFinite(r) || r <= 0) throw new Error('Invalid rate'); if (!cancelled) { setRate(r); setReward((usd * r).toFixed(2)) } }).catch(() => { if (!cancelled) { setRate(null); setReward('') } }).finally(() => { if (!cancelled) setQuoting(false) }); return () => { cancelled = true } }, [baseUsd, form.currency])
  const update = e => setForm({ ...form, [e.target.name]: e.target.value })
  async function submit(e) { e.preventDefault(); if (!reward) { alert('A live exchange quote is required'); return } try { const w = await platformApi.createWork({ ...form, reward_amount: Number(reward) }); setDone(`Draft ${w.id} created. Open My Created Work to edit, publish or close it.`); setForm({ title: '', description: '', requirements: '', currency: 'BDT', max_workers: 1, deadline: '' }); setBaseUsd(''); setReward('') } catch (e) { alert(e.message) } }
  return <><h1>Create Work</h1><p style={{ color: '#64748b' }}>Create a draft first. Reward is calculated from USD using the live exchange system; the selected currency and calculated amount are stored together.</p><form onSubmit={submit} style={card}><label>Title<input name="title" value={form.title} onChange={update} style={input} required /></label><label>Description<textarea name="description" value={form.description} onChange={update} style={input} rows={5} required /></label><label>Requirements<textarea name="requirements" value={form.requirements} onChange={update} style={input} rows={3} /></label><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 10 }}><label>Base reward (USD)<input type="number" min="0.00000001" step="any" value={baseUsd} onChange={e => setBaseUsd(e.target.value)} style={input} required /></label><label>Currency<select name="currency" value={form.currency} onChange={update} style={input}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label><label>Calculated reward ({form.currency})<input value={reward} readOnly style={input} /></label><label>Max workers<input type="number" min="1" max="1000" name="max_workers" value={form.max_workers} onChange={update} style={input} /></label></div><small>{rate ? `Live rate: 1 USD = ${rate} ${form.currency}` : quoting ? 'Updating live rate…' : baseUsd ? 'Live rate unavailable' : 'Enter a USD reward to calculate'}</small><label>Deadline<input type="datetime-local" name="deadline" value={form.deadline} onChange={update} style={input} /></label><button type="submit" style={{ marginTop: 12 }} disabled={!reward || quoting}>Create draft</button>{done && <p>{done}</p>}</form></>
}

export function WorkDetail() {
  const { id } = useParams(); const [work, setWork] = useState(null); const [proof, setProof] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { platformApi.work(id).then(setWork).catch(e => alert(e.message)) }, [id])
  if (!work) return <main style={box}><WorkNav /><p>Loading work…</p></main>
  async function accept() { setBusy(true); try { await platformApi.acceptWork(id); setWork(await platformApi.work(id)); alert('Work accepted.') } catch (e) { alert(e.message) } finally { setBusy(false) } }
  async function submit() { if (!proof.trim()) return; setBusy(true); try { await platformApi.submitWork(id, proof); setProof(''); alert('Submission sent for review.') } catch (e) { alert(e.message) } finally { setBusy(false) } }
  return <main style={box}><WorkNav /><h1>{work.title}</h1><article style={card}><p>{work.description}</p>{work.requirements && <p><b>Requirements:</b> {work.requirements}</p>}<p><b>Reward:</b> {work.reward_amount} {work.currency} · <b>Total amount:</b> {work.total_amount} {work.currency}</p><p><b>Total tasks:</b> {work.total_tasks} · <b>Active:</b> {work.active_tasks} · <b>Completed:</b> {work.completed_tasks} · <b>Remaining:</b> {work.remaining_tasks}</p><p><b>Remaining amount:</b> {work.remaining_amount} {work.currency} · <b>Stage:</b> {work.status}</p>{work.deadline && <p><b>Deadline:</b> {new Date(work.deadline).toLocaleString()}</p>}{work.status === 'open' && <button disabled={busy} onClick={accept}>Accept work</button>}</article><article style={card}><h3>Submit result</h3><textarea rows={5} value={proof} onChange={e => setProof(e.target.value)} placeholder="Evidence, result URL, notes, or proof" style={input} /><button disabled={busy || !proof.trim()} onClick={submit} style={{ marginTop: 8 }}>Submit</button></article></main>
}

function Manage() {
  const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const load = () => platformApi.works('all').then(setItems).catch(e => alert(e.message)); useEffect(load, [])
  async function action(id, fn) { try { await fn(id); load() } catch (e) { alert(e.message) } }
  async function save(e) { e.preventDefault(); try { await platformApi.updateWork(editing.id, editing); setEditing(null); load() } catch (e) { alert(e.message) } }
  return <><h1>My Created Work</h1><p style={{ color: '#64748b' }}>Directly edit, publish, close, or open each work. Totals update from assignments.</p>{items.map(w => <article key={w.id} style={card}><h3><Link to={`/work/${w.id}`}>{w.title}</Link></h3><p><b>Stage:</b> {w.status} · <b>Reward:</b> {w.reward_amount} {w.currency} · <b>Total:</b> {w.total_amount} {w.currency} · <b>Remaining:</b> {w.remaining_tasks}</p><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><Link to={`/work/${w.id}`}>Open</Link>{['draft','open'].includes(w.status) && <button onClick={() => setEditing({ ...w })}>Edit</button>}{w.status === 'draft' && <button onClick={() => action(w.id, platformApi.publishWork)}>Publish</button>}{!['closed','completed'].includes(w.status) && <button onClick={() => action(w.id, platformApi.closeWork)}>Close</button>}</div></article>)}{editing && <form onSubmit={save} style={card}><h3>Edit work</h3><input value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} style={input} required /><textarea value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} rows={4} style={input} required /><textarea value={editing.requirements || ''} onChange={e => setEditing({ ...editing, requirements: e.target.value })} rows={3} style={input} /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 10 }}><input type="number" min="0.00000001" step="any" value={editing.reward_amount} onChange={e => setEditing({ ...editing, reward_amount: e.target.value })} style={input} /><select value={editing.currency} onChange={e => setEditing({ ...editing, currency: e.target.value })} style={input}>{CURRENCIES.map(c => <option key={c}>{c}</option>)}</select><input type="number" min="1" max="1000" value={editing.max_workers} onChange={e => setEditing({ ...editing, max_workers: e.target.value })} style={input} /></div><button type="submit">Save changes</button> <button type="button" onClick={() => setEditing(null)}>Cancel</button></form>}</>
}

function Active() { const [items, setItems] = useState([]); const [proof, setProof] = useState({}); useEffect(() => { platformApi.activeWorks().then(setItems).catch(e => alert(e.message)) }, []); async function submit(id) { try { await platformApi.submitWork(id, proof[id] || ''); alert('Submission sent'); setProof({ ...proof, [id]: '' }) } catch (e) { alert(e.message) } } return <><h1>My Active Works</h1>{items.map(x => <article key={x.assignment_id} style={card}><h3><Link to={`/work/${x.work.id}`}>{x.work.title}</Link></h3><p>{x.work.description}</p><p>Total: {x.work.total_tasks} tasks · Remaining: {x.work.remaining_tasks} · Reward: {x.work.reward_amount} {x.work.currency}</p><textarea rows={4} value={proof[x.work.id] || ''} onChange={e => setProof({ ...proof, [x.work.id]: e.target.value })} placeholder="Evidence, result URL, notes, or proof" style={input} /><button onClick={() => submit(x.work.id)} style={{ marginTop: 8 }}>Submit result</button></article>)}{items.length === 0 && <div style={card}>You have no active work.</div>}</> }
function Submissions() { const [items, setItems] = useState([]); useEffect(() => { platformApi.submissions().then(setItems).catch(e => alert(e.message)) }, []); return <><h1>My Submission</h1>{items.map(x => <article key={x.id} style={card}><b>{x.status.toUpperCase()}</b><p><Link to={`/work/${x.work_id}`}>Work: {x.work_id}</Link></p><p>{x.proof}</p>{x.review_note && <p>Review: {x.review_note}</p>}</article>)}{items.length === 0 && <div style={card}>No submissions yet.</div>}</> }
function Review() { const [items, setItems] = useState([]); const [busy, setBusy] = useState({}); const load = () => platformApi.creatorSubmissions().then(setItems).catch(e => alert(e.message)); useEffect(load, []); async function review(id, decision) { setBusy({ ...busy, [id]: true }); try { await platformApi.reviewSubmission(id, decision, decision === 'approved' ? 'Approved by creator' : 'Rejected by creator'); await load() } catch (e) { alert(e.message) } finally { setBusy({ ...busy, [id]: false }) } } return <><h1>Work Review</h1><p>Review evidence. Approval settles the reward through the payment ledger.</p>{items.map(x => <article key={x.id} style={card}><div><Link to={`/work/${x.work.id}`}><b>{x.work.title}</b></Link> · {x.status}</div><p><b>Worker:</b> {x.worker_id}</p><p style={{ whiteSpace: 'pre-wrap' }}>{x.proof}</p>{x.status === 'pending' && <div style={{ display: 'flex', gap: 8 }}><button disabled={busy[x.id]} onClick={() => review(x.id, 'approved')}>Approve & pay</button><button disabled={busy[x.id]} onClick={() => review(x.id, 'rejected')}>Reject</button></div>}</article>)}{items.length === 0 && <div style={card}>No creator submissions.</div>}</> }

export default function WorkHub() { const path = useLocation().pathname; return <main style={box}><WorkNav />{path === '/create-work' ? <Create /> : path === '/my-created-work' ? <Manage /> : path === '/my-active-work' ? <Active /> : path === '/my-submission' ? <Submissions /> : path === '/work-review' ? <Review /> : <Browse />}</main> }
