import React, { useEffect, useRef, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { getExchangeRate } from '../lib/financialApi'
import { platformApi } from '../lib/platformApi'

const box={maxWidth:1100,margin:'0 auto',padding:'28px 16px 80px',fontFamily:'system-ui,sans-serif'}
const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:14,padding:18,marginBottom:14}
const input={width:'100%',boxSizing:'border-box',padding:10,marginTop:5,border:'1px solid #cbd5e1',borderRadius:8}
const CURRENCIES=['USD','BDT','EUR','GBP','INR','AUD','CAD','SGD','AED','SAR','JPY','CNY','HKD','MYR','THB','IDR','PKR','NPR','LKR','QAR','KWD','OMR','NZD','CHF','SEK','NOK','DKK','ZAR','TRY','BRL']
const fmt=s=>{s=Number(s||0);return `${Math.floor(s/3600)}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function WorkNav(){return <nav style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:20}}><Link to="/work">Browse</Link><Link to="/create-work">Create Work</Link><Link to="/my-created-work">My Created Work</Link><Link to="/my-active-work">My Active Works</Link><Link to="/my-submission">My Submission</Link><Link to="/work-review">Work Review</Link></nav>}
function Browse(){const[works,setWorks]=useState([]);useEffect(()=>{platformApi.works('open').then(setWorks).catch(e=>alert(e.message))},[]);return <><h1>Work</h1><p>Published tasks now open directly into an evidence-backed work session.</p>{works.map(w=><article key={w.id} style={card}><h3><Link to={`/work/${w.id}`}>{w.title}</Link></h3><p>{w.description}</p><p><b>Total:</b> {w.total_tasks} · <b>Active:</b> {w.active_tasks} · <b>Completed:</b> {w.completed_tasks} · <b>Remaining:</b> {w.remaining_tasks}</p><p><b>Reward:</b> {w.reward_amount} {w.currency} · <b>Remaining amount:</b> {w.remaining_amount} {w.currency}</p><Link to={`/work/${w.id}`}>Open work</Link></article>)}{!works.length&&<div style={card}>No published work is available.</div>}</>}
function Create(){const[currencies,setCurrencies]=useState(CURRENCIES);const[baseUsd,setBaseUsd]=useState('');const[reward,setReward]=useState('');const[rate,setRate]=useState(null);const[form,setForm]=useState({title:'',description:'',requirements:'',currency:'BDT',max_workers:1,deadline:''});const[done,setDone]=useState('');useEffect(()=>{platformApi.currencies().then(x=>x?.currencies?.length&&setCurrencies(x.currencies)).catch(()=>{})},[]);useEffect(()=>{let stop=false;const n=Number(baseUsd);if(!n){setReward('');setRate(null);return}if(form.currency==='USD'){setReward(n.toFixed(2));setRate(1);return}getExchangeRate('USD',form.currency).then(x=>{const r=Number(x?.rate);if(!stop&&r>0){setRate(r);setReward((n*r).toFixed(2))}}).catch(()=>!stop&&setReward(''));return()=>{stop=true}},[baseUsd,form.currency]);const up=e=>setForm({...form,[e.target.name]:e.target.value});async function submit(e){e.preventDefault();try{const w=await platformApi.createWork({...form,reward_amount:Number(reward)});setDone(`Draft ${w.id} created.`);setForm({title:'',description:'',requirements:'',currency:'BDT',max_workers:1,deadline:''});setBaseUsd('');setReward('')}catch(e){alert(e.message)}}return <><h1>Create Work</h1><form onSubmit={submit} style={card}><label>Title<input name="title" value={form.title} onChange={up} style={input} required/></label><label>Description<textarea name="description" value={form.description} onChange={up} style={input} rows={4} required/></label><label>Requirements<textarea name="requirements" value={form.requirements} onChange={up} style={input} rows={3}/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><label>Base reward USD<input type="number" min="0.00000001" step="any" value={baseUsd} onChange={e=>setBaseUsd(e.target.value)} style={input} required/></label><label>Currency<select name="currency" value={form.currency} onChange={up} style={input}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label>Reward<input value={reward} readOnly style={input}/></label><label>Max workers<input name="max_workers" type="number" min="1" max="1000" value={form.max_workers} onChange={up} style={input}/></label></div><small>{rate?`Live FX: 1 USD = ${rate} ${form.currency}`:'Enter the base reward to obtain the live FX quote.'}</small><label>Deadline<input name="deadline" type="datetime-local" value={form.deadline} onChange={up} style={input}/></label><button disabled={!reward}>Create draft</button>{done&&<p>{done}</p>}</form></>}

function Capture({onCaptured}){const[busy,setBusy]=useState(false);async function capture(){setBusy(true);let stream;try{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Screen capture is not supported by this browser');stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=stream.getVideoTracks()[0];const settings=track.getSettings();const v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>setTimeout(r,250));const c=document.createElement('canvas');c.width=settings.width||1280;c.height=settings.height||720;c.getContext('2d').drawImage(v,0,0,c.width,c.height);onCaptured(c.toDataURL('image/jpeg',0.72));track.stop()}catch(e){alert(e.message)}finally{if(stream)stream.getTracks().forEach(t=>t.stop());setBusy(false)}}return <button onClick={capture} disabled={busy}>{busy?'Capturing…':'Capture required evidence'}</button>}

export function WorkDetail(){const{id}=useParams();const[work,setWork]=useState(null);const[cfg,setCfg]=useState(null);const[session,setSession]=useState(null);const[evidence,setEvidence]=useState([]);const[busy,setBusy]=useState(false);const[player,setPlayer]=useState(null);const[config,setConfig]=useState({task_url:'',media_url:'',media_type:'none',required_watch_seconds:0,watch_rate_per_minute:'0',rate_currency:'BDT',rate_rules:[],social_rates:{}});const lastPlaying=useRef(false);useEffect(()=>{Promise.all([platformApi.work(id),platformApi.workConfig(id)]).then(([w,c])=>{setWork(w);setCfg(c);setConfig({...config,...c})}).catch(e=>alert(e.message))},[id]);useEffect(()=>{if(session?.stage!=='working')return;const tick=async()=>{try{const x=await platformApi.heartbeatWorkSession(session.id,{visible:document.visibilityState==='visible',playing:!!lastPlaying.current,position:player?.currentTime||0,ready:!!player});setSession(x)}catch(e){console.warn(e)}};tick();const t=setInterval(tick,10000);return()=>clearInterval(t)},[session?.id,session?.stage,player]);useEffect(()=>{if(session?.stage==='working')window.onbeforeunload=()=>'Work session is active';else window.onbeforeunload=null;return()=>{window.onbeforeunload=null}},[session?.stage]);
 if(!work)return <main style={box}><WorkNav/><p>Loading work…</p></main>
 async function ensureSession(){let s=session;if(!s)s=await platformApi.createWorkSession(id);setSession(s);return s}
 async function accept(){setBusy(true);try{await platformApi.acceptWork(id);setWork(await platformApi.work(id))}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function evidenceFor(s,kind,data){await platformApi.addWorkEvidence(s.id,{kind,data_url:data,title:`${kind} work evidence`,metadata:{captured_from:'browser_display_capture',timestamp:new Date().toISOString()}});setEvidence(await platformApi.workEvidence(id))}
 async function beforeCaptured(data){const s=await ensureSession();await evidenceFor(s,'before',data)}
 async function start(){setBusy(true);try{const s=await ensureSession();const data=await new Promise(resolve=>{const f=document.createElement('input');f.type='file';f.accept='image/*';f.capture='environment';f.onchange=()=>resolve(null);f.click()});void data;await platformApi.startWorkSession(s.id);setSession(await platformApi.workSession(s.id));setEvidence(await platformApi.workEvidence(id))}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function finish(){setBusy(true);try{const data=await new Promise(resolve=>{const f=document.createElement('input');f.type='file';f.accept='image/*';f.capture='environment';f.onchange=()=>resolve(null);f.click()});void data;const x=await platformApi.finishWorkSession(session.id);setSession(x);alert(`Finished. Verified watch time: ${fmt(x.eligible_watch_seconds)}; calculated reward: ${x.calculated_amount} ${x.currency}`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function submit(){setBusy(true);try{const x=await platformApi.submitWorkSession(session.id);setSession({...session,stage:'submitted'});alert(`Submitted. Calculated reward: ${x.calculated_amount} ${x.currency}`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function social(type){try{await platformApi.recordWorkEvent(session.id,{event_type:type,payload:{verification:'self_reported',note:'External action is recorded as evidence only; no automatic reward claim'}});alert(`${type} recorded as evidence (not independently verified).`)}catch(e){alert(e.message)}}
 async function saveConfig(e){e.preventDefault();try{const x=await platformApi.saveWorkConfig(id,{...config,required_watch_seconds:Number(config.required_watch_seconds),watch_rate_per_minute:Number(config.watch_rate_per_minute)});setCfg(x);alert('Task configuration saved.')}catch(e){alert(e.message)}}
 const media=config.media_url&&((config.media_type==='video')?<video controls width="100%" style={{maxHeight:500}} src={config.media_url} onPlay={()=>{lastPlaying.current=true;session&&platformApi.recordWorkEvent(session.id,{event_type:'play',payload:{source:config.media_url}}).catch(()=>{})}} onPause={()=>{lastPlaying.current=false;session&&platformApi.recordWorkEvent(session.id,{event_type:'pause'}).catch(()=>{})}}/>:<iframe title="work media" src={config.media_url} style={{width:'100%',height:480,border:0}} onLoad={()=>setPlayer(null)}/>)
 return <main style={box}><WorkNav/><h1>{work.title}</h1><article style={card}><p>{work.description}</p>{work.requirements&&<p><b>Requirements:</b> {work.requirements}</p>}<p><b>Accounting:</b> Total {work.total_tasks} · Completed {work.completed_tasks} · Active {work.active_tasks} · Remaining {work.remaining_tasks} · Total reward {work.total_amount} {work.currency} · Remaining {work.remaining_amount} {work.currency}</p>{work.status==='open'&&<button disabled={busy} onClick={accept}>Accept work</button>}</article>
 <article style={card}><h2>Work lifecycle</h2>{!session&&<p>Accept the task, then open the Before Work stage.</p>}{session?.stage==='before'&&<><p><b>Before Work</b> — required evidence must be captured before starting.</p><Capture onCaptured={beforeCaptured}/><button disabled={busy} onClick={start} style={{marginLeft:8}}>Start Work</button></>}{session?.stage==='working'&&<><p><b>Working</b> · elapsed {fmt(session.work_seconds)} · verified watch {fmt(session.eligible_watch_seconds)} · interaction {fmt(session.interaction_seconds)}</p><p>Watch reward: {session.calculated_amount} {session.currency}</p>{media}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{['like','comment','share','follow','rating'].map(x=><button key={x} onClick={()=>social(x)}>{x}</button>)}<button disabled={busy} onClick={finish}>End Work</button></div></>}{session?.stage==='finished'&&<><p><b>Finished</b> · work time {fmt(session.work_seconds)} · eligible watch {fmt(session.eligible_watch_seconds)}</p><p><b>Server-calculated amount:</b> {session.calculated_amount} {session.currency}</p><button disabled={busy} onClick={submit}>Submit for review</button></>}{session?.stage==='submitted'&&<p><b>Submitted</b> — awaiting creator review and verified reward settlement.</p>}</article>
 <article style={card}><h2>Task / video rate</h2><form onSubmit={saveConfig}><label>Task/link URL<input value={config.task_url||''} onChange={e=>setConfig({...config,task_url:e.target.value})} style={input}/></label><label>Video/live-video/YouTube URL<input value={config.media_url||''} onChange={e=>setConfig({...config,media_url:e.target.value})} style={input}/></label><label>Media type<select value={config.media_type||'none'} onChange={e=>setConfig({...config,media_type:e.target.value})} style={input}><option value="none">None</option><option value="video">Direct video</option><option value="youtube">YouTube</option><option value="live">Live video</option></select></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><label>Required watch seconds<input type="number" min="0" value={config.required_watch_seconds||0} onChange={e=>setConfig({...config,required_watch_seconds:e.target.value})} style={input}/></label><label>Verified watch rate / minute<input type="number" min="0" step="any" value={config.watch_rate_per_minute||0} onChange={e=>setConfig({...config,watch_rate_per_minute:e.target.value})} style={input}/></label><label>Rate currency<input value={config.rate_currency||work.currency} onChange={e=>setConfig({...config,rate_currency:e.target.value})} style={input}/></label></div><p><small>For external/YouTube players, only playback signals actually exposed to the browser/API can be treated as verified. Self-reported social actions are never automatically paid.</small></p><button>Save task configuration</button></form></article>
 <article style={card}><h2>Evidence</h2>{evidence.map(e=><div key={e.id} style={{borderTop:'1px solid #e2e8f0',padding:'10px 0'}}><b>{e.kind}</b> · {new Date(e.captured_at).toLocaleString()} {e.data_url&&<a href={e.data_url} download={`work-${e.kind}-${e.id}.jpg`}> Download</a>}<p>{e.title}</p></div>)}{!evidence.length&&<p>No evidence captured yet.</p>}</article></main>}

function Manage(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.works('all').then(setItems).catch(e=>alert(e.message))},[]);return <><h1>My Created Work</h1>{items.map(w=><article key={w.id} style={card}><h3><Link to={`/work/${w.id}`}>{w.title}</Link></h3><p>Stage: {w.status} · Total {w.total_amount} {w.currency} · Remaining {w.remaining_tasks}</p><Link to={`/work/${w.id}`}>Manage work</Link></article>)}</>}
function Active(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.activeWorks().then(setItems).catch(e=>alert(e.message))},[]);return <><h1>My Active Works</h1>{items.map(x=><article key={x.assignment_id} style={card}><h3><Link to={`/work/${x.work.id}`}>{x.work.title}</Link></h3><p>Open the direct work URL to continue the persisted evidence/timing session.</p></article>)}{!items.length&&<div style={card}>You have no active work.</div>}</>}
function Submissions(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.submissions().then(setItems).catch(e=>alert(e.message))},[]);return <><h1>My Submission</h1>{items.map(x=><article key={x.id} style={card}><b>{x.status.toUpperCase()}</b><p><Link to={`/work/${x.work_id}`}>Work {x.work_id}</Link></p><pre style={{whiteSpace:'pre-wrap'}}>{x.proof}</pre>{x.review_note&&<p>{x.review_note}</p>}</article>)}</>}
function Review(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.creatorSubmissions().then(setItems).catch(e=>alert(e.message))},[]);async function approve(id){try{await platformApi.approveVerifiedSubmission(id);setItems(await platformApi.creatorSubmissions())}catch(e){alert(e.message)}}return <><h1>Work Review</h1><p>Verified-work submissions settle the server-calculated amount, not a client-entered reward.</p>{items.map(x=><article key={x.id} style={card}><Link to={`/work/${x.work.id}`}><b>{x.work.title}</b></Link><p>Worker: {x.worker_id}</p><pre style={{whiteSpace:'pre-wrap'}}>{x.proof}</pre>{x.status==='pending'&&<button onClick={()=>approve(x.id)}>Approve & settle verified reward</button>}</article>)}</>}
export default function WorkHub(){const path=useLocation().pathname;return <main style={box}><WorkNav/>{path==='/create-work'?<Create/>:path==='/my-created-work'?<Manage/>:path==='/my-active-work'?<Active/>:path==='/my-submission'?<Submissions/>:path==='/work-review'?<Review/>:path.startsWith('/work/')?<WorkDetail/>:<Browse/>}</main>}
