import React, { useEffect, useRef, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { getExchangeRate } from '../lib/financialApi'
import { platformApi } from '../lib/platformApi'

const box={maxWidth:1100,margin:'0 auto',padding:'28px 16px 80px',fontFamily:'system-ui,sans-serif'}
const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:14,padding:18,marginBottom:14}
const input={width:'100%',boxSizing:'border-box',padding:10,marginTop:5,border:'1px solid #cbd5e1',borderRadius:8}
const CURRENCIES=['USD','BDT','EUR','GBP','INR','AUD','CAD','SGD','AED','SAR','JPY','CNY','HKD','MYR','THB','IDR','PKR','NPR','LKR','QAR','KWD','OMR','NZD','CHF','SEK','NOK','DKK','ZAR','TRY','BRL']
const fmt=s=>{s=Math.max(0,Number(s||0));return `${Math.floor(s/3600)}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function WorkNav(){return <nav style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:20}}><Link to="/work">Browse</Link><Link to="/create-work">Create Work</Link><Link to="/my-created-work">My Created Work</Link><Link to="/my-active-work">My Active Works</Link><Link to="/my-submission">My Submission</Link><Link to="/work-review">Work Review</Link></nav>}

function Browse(){const[works,setWorks]=useState([]);useEffect(()=>{platformApi.works('open').then(setWorks).catch(e=>alert(e.message))},[]);return <><h1>Work</h1><p>Published tasks open directly into evidence-backed sessions.</p>{works.map(w=><article key={w.id} style={card}><h3><Link to={`/work/${w.id}`}>{w.title}</Link></h3><p>{w.description}</p><p><b>Tasks:</b> {w.total_tasks} · <b>Completed:</b> {w.completed_tasks} · <b>Active:</b> {w.active_tasks} · <b>Remaining:</b> {w.remaining_tasks}</p><p><b>Total reward:</b> {w.total_amount} {w.currency} · <b>Remaining:</b> {w.remaining_amount} {w.currency}</p><Link to={`/work/${w.id}`}>Open work</Link></article>)}{!works.length&&<div style={card}>No published work is available.</div>}</>}

function Create(){const[currencies,setCurrencies]=useState(CURRENCIES);const[baseUsd,setBaseUsd]=useState('');const[reward,setReward]=useState('');const[rate,setRate]=useState(null);const[form,setForm]=useState({title:'',description:'',requirements:'',currency:'BDT',max_workers:1,deadline:''});const[done,setDone]=useState('');useEffect(()=>{platformApi.currencies().then(x=>x?.currencies?.length&&setCurrencies(x.currencies)).catch(()=>{})},[]);useEffect(()=>{let stop=false;const n=Number(baseUsd);if(!n){setReward('');setRate(null);return}if(form.currency==='USD'){setReward(n.toFixed(2));setRate(1);return}getExchangeRate('USD',form.currency).then(x=>{const r=Number(x?.rate);if(!stop&&r>0){setRate(r);setReward((n*r).toFixed(2))}}).catch(()=>!stop&&setReward(''));return()=>{stop=true}},[baseUsd,form.currency]);const up=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));async function submit(e){e.preventDefault();try{const w=await platformApi.createWork({...form,reward_amount:Number(reward)});setDone(`Draft ${w.id} created.`);setForm({title:'',description:'',requirements:'',currency:'BDT',max_workers:1,deadline:''});setBaseUsd('');setReward('')}catch(e){alert(e.message)}}return <><h1>Create Work</h1><form onSubmit={submit} style={card}><label>Title<input name="title" value={form.title} onChange={up} style={input} required/></label><label>Description<textarea name="description" value={form.description} onChange={up} style={input} rows={4} required/></label><label>Requirements<textarea name="requirements" value={form.requirements} onChange={up} style={input} rows={3}/></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><label>Base reward USD<input type="number" min="0.00000001" step="any" value={baseUsd} onChange={e=>setBaseUsd(e.target.value)} style={input} required/></label><label>Currency<select name="currency" value={form.currency} onChange={up} style={input}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label>Reward<input value={reward} readOnly style={input}/></label><label>Max workers<input name="max_workers" type="number" min="1" max="1000" value={form.max_workers} onChange={up} style={input}/></label></div><small>{rate?`Live FX: 1 USD = ${rate} ${form.currency}`:'Enter a base reward for the live FX quote.'}</small><label>Deadline<input name="deadline" type="datetime-local" value={form.deadline} onChange={up} style={input}/></label><button disabled={!reward}>Create draft</button>{done&&<p>{done}</p>}</form></>}

async function captureEvidenceData(){
  if(navigator.mediaDevices?.getDisplayMedia){
    let stream
    try{stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=stream.getVideoTracks()[0];const settings=track.getSettings();const v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>setTimeout(r,250));const c=document.createElement('canvas');c.width=settings.width||1280;c.height=settings.height||720;c.getContext('2d').drawImage(v,0,0,c.width,c.height);return c.toDataURL('image/jpeg',0.72)}finally{stream?.getTracks().forEach(t=>t.stop())}
  }
  return await new Promise((resolve,reject)=>{const f=document.createElement('input');f.type='file';f.accept='image/*';f.capture='environment';f.onchange=()=>{const file=f.files?.[0];if(!file)return reject(new Error('Evidence capture was cancelled'));if(file.size>6_000_000)return reject(new Error('Evidence image is too large'));const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Could not read evidence image'));r.readAsDataURL(file)};f.click()})
}

function EvidenceCapture({label,onCaptured,disabled}){const[busy,setBusy]=useState(false);async function run(){setBusy(true);try{const data=await captureEvidenceData();await onCaptured(data)}catch(e){alert(e.message)}finally{setBusy(false)}}return <button disabled={disabled||busy} onClick={run}>{busy?'Capturing…':label}</button>}

function YouTubePlayer({url,onState,onPosition}){const ref=useRef(null);const player=useRef(null);useEffect(()=>{let cancelled=false;const id=(()=>{try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1);return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()}catch{return null}})();if(!id)return()=>{};const load=()=>{if(cancelled||!window.YT?.Player||!ref.current)return;player.current=new window.YT.Player(ref.current,{videoId:id,width:'100%',height:'480',playerVars:{playsinline:1,enablejsapi:1,origin:window.location.origin},events:{onStateChange:e=>{onState(e.data===window.YT.PlayerState.PLAYING);if(e.data===window.YT.PlayerState.PAUSED||e.data===window.YT.PlayerState.ENDED)onState(false)}}})};if(window.YT?.Player)load();else{const old=document.querySelector('script[data-shopno-youtube]');if(!old){const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.dataset.shopnoYoutube='1';document.head.appendChild(s)}const timer=setInterval(()=>{if(window.YT?.Player){clearInterval(timer);load()}},250);return()=>{cancelled=true;clearInterval(timer);player.current?.destroy()}};const pos=setInterval(()=>{if(player.current?.getPlayerState&&player.current.getPlayerState()===window.YT.PlayerState.PLAYING)onPosition(player.current.getCurrentTime())},1000);return()=>{cancelled=true;clearInterval(pos);player.current?.destroy()}},[url,onState,onPosition]);return <div ref={ref} style={{width:'100%',maxWidth:900}}/>}

export function WorkDetail(){const{id}=useParams();const[work,setWork]=useState(null);const[session,setSession]=useState(null);const[evidence,setEvidence]=useState([]);const[busy,setBusy]=useState(false);const[config,setConfig]=useState({task_url:'',media_url:'',media_type:'none',required_watch_seconds:0,watch_rate_per_minute:'0',rate_currency:'BDT',rate_rules:[],social_rates:{}});const[playing,setPlaying]=useState(false);const[position,setPosition]=useState(0);const videoRef=useRef(null);const playingRef=useRef(false);const positionRef=useRef(0);useEffect(()=>{platformApi.work(id).then(async w=>{setWork(w);try{const c=await platformApi.workConfig(id);setConfig(c);const s=await platformApi.createWorkSession(id);setSession(s);setEvidence(await platformApi.workEvidence(id))}catch(e){try{setEvidence(await platformApi.workEvidence(id))}catch{}}}).catch(e=>alert(e.message))},[id]);useEffect(()=>{playingRef.current=playing},[playing]);useEffect(()=>{positionRef.current=position},[position]);useEffect(()=>{if(session?.stage!=='working')return;const tick=async()=>{try{const x=await platformApi.heartbeatWorkSession(session.id,{visible:document.visibilityState==='visible',playing:playingRef.current,position:positionRef.current,ready:!!config.media_url});setSession(x)}catch(e){console.warn(e)}};tick();const t=setInterval(tick,10000);return()=>clearInterval(t)},[session?.id,session?.stage,config.media_url]);useEffect(()=>{if(session?.stage==='working')window.onbeforeunload=()=>'Work session is active';else window.onbeforeunload=null;return()=>{window.onbeforeunload=null}},[session?.stage]);
 if(!work)return <main style={box}><WorkNav/><p>Loading work…</p></main>
 async function reloadEvidence(){setEvidence(await platformApi.workEvidence(id))}
 async function accept(){setBusy(true);try{await platformApi.acceptWork(id);setWork(await platformApi.work(id));setSession(await platformApi.createWorkSession(id))}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function saveEvidence(s,kind,data){await platformApi.addWorkEvidence(s.id,{kind,data_url:data,title:`${kind} work evidence`,metadata:{captured_from:navigator.mediaDevices?.getDisplayMedia?'screen_or_camera':'camera_or_file',captured_at:new Date().toISOString()}});await reloadEvidence()}
 async function beforeCaptured(data){const s=session||await platformApi.createWorkSession(id);setSession(s);await saveEvidence(s,'before',data)}
 async function start(){setBusy(true);try{const s=session||await platformApi.createWorkSession(id);if(!evidence.some(e=>e.kind==='before'))throw new Error('Capture the required Before Work evidence first');const data=await captureEvidenceData();await saveEvidence(s,'start',data);const x=await platformApi.startWorkSession(s.id);setSession(x);await reloadEvidence()}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function finish(){setBusy(true);try{if(!session)throw new Error('No active work session');const data=await captureEvidenceData();await saveEvidence(session,'end',data);const x=await platformApi.finishWorkSession(session.id);setSession(x);alert(`Finished. Verified watch: ${fmt(x.eligible_watch_seconds)} · ${x.calculated_amount} ${x.currency}`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function submit(){setBusy(true);try{const x=await platformApi.submitWorkSession(session.id);setSession({...session,stage:'submitted'});alert(`Submitted. Server-calculated reward: ${x.calculated_amount} ${x.currency}`)}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function social(type){try{await platformApi.recordWorkEvent(session.id,{event_type:type,payload:{verification:'self_reported',reward_eligible:false}});alert(`${type} recorded as evidence only; it is not independently verified or automatically paid.`)}catch(e){alert(e.message)}}
 async function saveConfig(e){e.preventDefault();try{const x=await platformApi.saveWorkConfig(id,{...config,required_watch_seconds:Number(config.required_watch_seconds),watch_rate_per_minute:Number(config.watch_rate_per_minute)});setConfig(x);alert('Task configuration saved.')}catch(e){alert(e.message)}}
 async function viewEvidence(e){if(e.data_url)window.open(e.data_url,'_blank','noopener,noreferrer');else if(e.evidence_url)window.open(e.evidence_url,'_blank','noopener,noreferrer')}
 async function shareEvidence(e){const text=`${work.title} — ${e.kind} evidence — ${new Date(e.captured_at).toLocaleString()}`;try{if(navigator.share)await navigator.share({title:work.title,text,url:e.evidence_url||window.location.href});else{await navigator.clipboard.writeText(e.evidence_url||window.location.href);alert('Evidence link copied.') }}catch(err){if(err?.name!=='AbortError')alert(err.message)}}
 async function editEvidence(e){const title=window.prompt('Evidence title',e.title||e.kind);if(title===null)return;try{await platformApi.editWorkEvidence(e.id,{title});await reloadEvidence()}catch(err){alert(err.message)}}
 async function deleteEvidence(e){if(!window.confirm('Delete this evidence? The audit record will remain.'))return;try{await platformApi.deleteWorkEvidence(e.id);await reloadEvidence()}catch(err){alert(err.message)}}
 const directMedia=config.media_url&&config.media_type==='video'?<video ref={videoRef} controls playsInline width="100%" style={{maxHeight:500}} src={config.media_url} onTimeUpdate={()=>setPosition(videoRef.current?.currentTime||0)} onPlay={()=>{setPlaying(true);session&&platformApi.recordWorkEvent(session.id,{event_type:'play',payload:{source:config.media_url,verification:'browser_player'}}).catch(()=>{})}} onPause={()=>{setPlaying(false);session&&platformApi.recordWorkEvent(session.id,{event_type:'pause'}).catch(()=>{})}}/>:null
 const youtube=config.media_url&&config.media_type==='youtube'?<YouTubePlayer url={config.media_url} onState={setPlaying} onPosition={setPosition}/>:null
 const external=config.media_url&&config.media_type==='live'?<><iframe title="work media" src={config.media_url} style={{width:'100%',height:480,border:0}}/><small>External/live iframe playback is not automatically credited unless reliable player telemetry is available.</small></>:null
 const media=directMedia||youtube||external
 return <main style={box}><WorkNav/><h1>{work.title}</h1><article style={card}><p>{work.description}</p>{work.requirements&&<p><b>Requirements:</b> {work.requirements}</p>}<p><b>Accounting:</b> Tasks {work.total_tasks} · Completed {work.completed_tasks} · Active {work.active_tasks} · Remaining {work.remaining_tasks}</p><p><b>Reward:</b> Total {work.total_amount} {work.currency} · Remaining {work.remaining_amount} {work.currency}</p>{work.status==='open'&&<button disabled={busy} onClick={accept}>Accept work</button>}{config.task_url&&<p><a href={config.task_url} target="_blank" rel="noreferrer">Open task / target link</a></p>}</article>
 <article style={card}><h2>Work lifecycle</h2>{!session&&<p>Accept the work to create a persisted Before Work session.</p>}{session?.stage==='before'&&<><p><b>Before Work</b> — required evidence is saved server-side before Start Work is allowed.</p><EvidenceCapture label="Capture Before Work evidence" disabled={busy} onCaptured={beforeCaptured}/><button disabled={busy||!evidence.some(e=>e.kind==='before')} onClick={start} style={{marginLeft:8}}>Start Work</button></>}{session?.stage==='working'&&<><p><b>Working</b> · elapsed {fmt(session.work_seconds)} · verified watch {fmt(session.eligible_watch_seconds)} · interaction {fmt(session.interaction_seconds)}</p><p><b>Server-calculated amount:</b> {session.calculated_amount} {session.currency}</p>{media}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{['like','comment','share','follow','rating'].map(x=><button key={x} onClick={()=>social(x)}>{x}</button>)}<button disabled={busy} onClick={finish}>End Work</button></div><p><small>Only server-validated elapsed/playback telemetry contributes to verified watch reward. Social actions are recorded but not automatically rewarded.</small></p></>}{session?.stage==='finished'&&<><p><b>Finished</b> · work {fmt(session.work_seconds)} · verified watch {fmt(session.eligible_watch_seconds)}</p><p><b>Server-calculated amount:</b> {session.calculated_amount} {session.currency}</p><button disabled={busy} onClick={submit}>Submit for review</button></>}{session?.stage==='submitted'&&<p><b>Submitted</b> — awaiting creator review and verified reward settlement.</p>}</article>
 <article style={card}><h2>Task / video rate configuration</h2><form onSubmit={saveConfig}><label>Task/link URL<input value={config.task_url||''} onChange={e=>setConfig(c=>({...c,task_url:e.target.value}))} style={input}/></label><label>Video/live-video/YouTube URL<input value={config.media_url||''} onChange={e=>setConfig(c=>({...c,media_url:e.target.value}))} style={input}/></label><label>Media type<select value={config.media_type||'none'} onChange={e=>setConfig(c=>({...c,media_type:e.target.value}))} style={input}><option value="none">None</option><option value="video">Direct video</option><option value="youtube">YouTube</option><option value="live">Live video / external</option></select></label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><label>Required verified watch seconds<input type="number" min="0" value={config.required_watch_seconds||0} onChange={e=>setConfig(c=>({...c,required_watch_seconds:e.target.value}))} style={input}/></label><label>Verified watch rate / minute<input type="number" min="0" step="any" value={config.watch_rate_per_minute||0} onChange={e=>setConfig(c=>({...c,watch_rate_per_minute:e.target.value}))} style={input}/></label><label>Rate currency<input value={config.rate_currency||work.currency} onChange={e=>setConfig(c=>({...c,rate_currency:e.target.value}))} style={input}/></label></div><p><small>Rate rules can vary by configured time stage. Rewards are calculated on the server from eligible watch seconds; client-provided reward/duration is never accepted.</small></p><button>Save task configuration</button></form></article>
 <article style={card}><h2>Evidence</h2>{evidence.map(e=><div key={e.id} style={{borderTop:'1px solid #e2e8f0',padding:'10px 0'}}><b>{e.kind}</b> · {new Date(e.captured_at).toLocaleString()}<p>{e.title||'Untitled evidence'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(e.data_url||e.evidence_url)&&<button onClick={()=>viewEvidence(e)}>View</button>}{e.data_url&&<a href={e.data_url} download={`work-${e.kind}-${e.id}.jpg`}>Download</a>}<button onClick={()=>shareEvidence(e)}>Share</button><button onClick={()=>editEvidence(e)}>Edit</button><button onClick={()=>deleteEvidence(e)}>Delete</button></div></div>)}{!evidence.length&&<p>No evidence captured yet.</p>}</article></main>
}

function Manage(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.works('all').then(setItems).catch(e=>alert(e.message))},[]);return <><h1>My Created Work</h1>{items.map(w=><article key={w.id} style={card}><h3><Link to={`/work/${w.id}`}>{w.title}</Link></h3><p>Status: {w.status} · Total {w.total_amount} {w.currency} · Remaining tasks {w.remaining_tasks}</p><Link to={`/work/${w.id}`}>Manage directly</Link></article>)}{!items.length&&<div style={card}>No created work found.</div>}</>}
function Active(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.activeWorks().then(setItems).catch(e=>alert(e.message))},[]);return <><h1>My Active Works</h1>{items.map(x=><article key={x.assignment_id} style={card}><h3><Link to={`/work/${x.work.id}`}>{x.work.title}</Link></h3><p>Persisted session: open the direct URL to continue.</p></article>)}{!items.length&&<div style={card}>You have no active work.</div>}</>}
function Submissions(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.submissions().then(setItems).catch(e=>alert(e.message))},[]);return <><h1>My Submission</h1>{items.map(x=><article key={x.id} style={card}><b>{String(x.status).toUpperCase()}</b><p><Link to={`/work/${x.work_id}`}>Open work {x.work_id}</Link></p><pre style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{x.proof||''}</pre></article>)}{!items.length&&<div style={card}>No submissions found.</div>}</>}
function Review(){const[items,setItems]=useState([]);useEffect(()=>{platformApi.creatorSubmissions().then(setItems).catch(e=>alert(e.message))},[]);async function approve(id){try{await platformApi.approveVerifiedSubmission(id);setItems(await platformApi.creatorSubmissions())}catch(e){alert(e.message)}}return <><h1>Work Review</h1>{items.map(x=><article key={x.id} style={card}><b>{String(x.status).toUpperCase()}</b><p><Link to={`/work/${x.work_id}`}>Open work {x.work_id}</Link></p><pre style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{x.proof||''}</pre>{x.status==='pending'&&<button onClick={()=>approve(x.id)}>Approve & settle verified reward</button>}</article>)}{!items.length&&<div style={card}>No creator submissions.</div>}</>}

export default function WorkHub(){const path=useLocation().pathname;let content;if(path==='/work'||path==='/work/')content=<Browse/>;else if(path==='/create-work')content=<Create/>;else if(path==='/my-created-work')content=<Manage/>;else if(path==='/my-active-work')content=<Active/>;else if(path==='/my-submission')content=<Submissions/>;else if(path==='/work-review')content=<Review/>;else content=<WorkDetail/>;return <main style={box}><WorkNav/>{content}</main>}
