apiVersion: v1
kind: ConfigMap
metadata:
  name: interior-service-config
  namespace: shopno-platform
data:
  APP_NAME: "interior-service"
  APP_PORT: "8080"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  ENV: "production"
  PATH_PREFIX: "/"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4317"
  REDIS_HOST: "redis.shopno-data.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres.shopno-data.svc.cluster.local"
  POSTGRES_PORT: "5432"
  MINIO_ENDPOINT: "minio.shopno-data.svc.cluster.local:9000"
  KEYCLOAK_ISSUER: "https://auth.shopnoltd.dpdns.org/realms/shopnoltd"
  KEYCLOAK_CLIENT_ID: "interior-service"
