apiVersion: networking.k8s.io/v1

kind: Ingress


metadata:

  name: shopnoltd-ai-ingress


spec:

  rules:


  - host: ai.shopnoltd.dpdns.org


    http:


      paths:


      - path: /

        pathType: Prefix


        backend:


          service:


            name: shopnoltd-ai


            port:


              number: 80
