apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
      - image: live:latest
        imagePullPolicy: Never
        name: live
        ports:
        - containerPort: 8080
          protocol: TCP
