# generate-secret-files.sh — run from repo root
# Creates a secret.yaml for every service whose kustomization references it,
# pulling values from the root secrets-template.yaml when possible.

set -e
TEMPLATE="secrets-template.yaml"
[[ -f "$TEMPLATE" ]] || { echo "missing $TEMPLATE"; exit 1; }

# Default password for services without a specific entry
DEFAULT_PW="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"

created=0; skipped=0
for d in k8s/services/*/; do
  kust="$d/kustomization.yaml"
  [[ -f "$kust" ]] || continue
  grep -qE '^\s*-\s*secret\.yaml\s*$' "$kust" || continue
  [[ -f "$d/secret.yaml" ]] && { skipped=$((skipped+1)); continue; }
  
  svc=$(basename "$d")
  # extract namespace from kustomization
  ns=$(awk '/^namespace:[[:space:]]*/{print $2; exit}' "$kust")
  [[ -z "$ns" ]] && ns="default"
  # extract secret name from the deployment, or default to <svc>-secret
  secret_name=$(awk '/^\s*secretName:[[:space:]]*/{print $2; exit}' "$d/deployment.yaml" 2>/dev/null || true)
  [[ -z "$secret_name" ]] && secret_name="${svc}-secret"
  
  # try to find a matching key in the template
  # the template uses SERVICE_<UPPER>_PASSWORD or SERVICE_<UPPER>_DB_PASSWORD etc.
  up=$(echo "$svc" | tr 'a-z-' 'A-Z_')
  pw="$DEFAULT_PW"
  # a few common alternates to try
  for hint in "PASSWORD" "DB_PASSWORD" "ADMIN_PASSWORD" "JWT_SECRET" "API_KEY" "SECRET_KEY"; do
    if grep -qE "^[[:space:]]*${up}_${hint}:" "$TEMPLATE" 2>/dev/null; then
      pw=$(grep -E "^[[:space:]]*${up}_${hint}:" "$TEMPLATE" | head -1 \
           | sed -E "s/^[[:space:]]*[^:]+:[[:space:]]*//; s/[\"']//g")
      break
    fi
  done
  
  cat > "$d/secret.yaml" <<EOF
# Generated by generate-secret-files.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# TODO: replace placeholder values with real secrets from your password manager.
apiVersion: v1
kind: Secret
metadata:
  name: ${secret_name}
  namespace: ${ns}
type: Opaque
stringData:
  password: "${pw}"
  username: "${svc}"
  admin-password: "${pw}"
  jwt-secret: "${pw}"
  db-password: "${pw}"
  api-key: "${pw}"
EOF
  created=$((created+1))
done

echo "Created $created secret.yaml files, skipped $skipped that already exist"
