apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf
  namespace: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kf
  template:
    metadata:
      labels:
        app: kf
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgis://kobo:kobo_pass@postgres.toolbox.svc.cluster.local:5432/kobodb
        - name: MONGO_HOST
          value: mongo.toolbox.svc.cluster.local
        - name: NGINX_STATIC_DIR
          value: /srv/static_collected
        - name: DJANGO_SECRET_KEY
          value: y42k8K4M-Ixcc0cGE-f7uLFNMGjrpVs9FK3iQje5UkmdGkWamW9k8Wlx0eoHNaSEQd0
        - name: KOBOFORM_URL
          value: http://kobo.shopnoltd.dpdns.org
        - name: KOBOCAT_URL
          value: http://kf.shopnoltd.dpdns.org
        - name: PUBLIC_DOMAIN_NAME
          value: shopnoltd.dpdns.org
        - name: KOBOCAT_PUBLIC_SUBDOMAIN
          value: kf
        image: kobotoolbox/kobocat:latest
        imagePullPolicy: Always
        name: kf
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /srv/init
          name: kf-init-scripts
        - mountPath: /srv/static_collected
          name: nginx-static
        - mountPath: /srv/src/kobocat/media
          name: kf-media
        - mountPath: /srv/src/kobocat/docker/kobocat.ini
          name: kobocat-ini-override
          subPath: kobocat.ini
      volumes:
      - configMap:
          defaultMode: 493
          name: kf-init-scripts
        name: kf-init-scripts
      - emptyDir: {}
        name: nginx-static
      - name: kf-media
        persistentVolumeClaim:
          claimName: kf-media-pvc
      - name: kobocat-ini-override
        configMap:
          name: kf-uwsgi-ini
