apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-config
  namespace: meet
data:
  ENABLE_AUTH: "1"
  AUTH_TYPE: "internal"
  XMPP_SERVER: "prosody"
  XMPP_BOSH_URL_BASE: "http://prosody:5280"
  XMPP_MUC_DOMAIN: "muc.meet.jitsi"
  JICOFO_AUTH_USER: "focus"
  JICOFO_AUTH_PASSWORD: "Shopnoltd2026"
  JVB_AUTH_USER: "jvb"
  JVB_AUTH_PASSWORD: "Shopnoltd2026"
  PUBLIC_URL: "https://meet.shopnoltd.dpdns.org"
