apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"redis","app.kubernetes.io/part-of":"shopnoltd"},"name":"redis","namespace":"shopno-data"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/name":"redis"},"type":"ClusterIP"}}
  creationTimestamp: "2026-07-19T10:57:38Z"
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: shopnoltd
  name: redis
  namespace: shopno-data
  resourceVersion: "9127"
  uid: 0e54728f-54ea-4c11-9232-026af6d0c6a1
spec:
  clusterIP: 10.96.8.105
  clusterIPs:
  - 10.96.8.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
