services:
  - type: web
    name: shopnoltd-backend
    env: docker
    plan: starter
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    branch: main
    envVars:
      - key: APP_NAME
        value: ShopNoLtd
      - key: APP_ENV
        value: production
      - key: APP_KEY
        fromFile: backend/.env
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://shopnoltd.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: shopnoltd_db
      - key: DB_USERNAME
        value: shopnouser
      - key: DB_PASSWORD
        value: Asad18081978#
    healthCheckPath: /health
    mounts:
      - type: volume
        name: shopnoltd-backend-storage
        mountPath: /var/www/html/storage

  - type: web
    name: shopnoltd-frontend
    env: docker
    plan: starter
    dockerfilePath: Dockerfile.frontend
    autoDeploy: true
    branch: main
    envVars:
      - key: REACT_APP_API_URL
        value: "https://shopnoltd-backend.onrender.com/api"
    healthCheckPath: /

databases:
  - name: shopnoltd-db
    engine: postgres
    plan: starter
    user: shopnouser
    password: Asad18081978#
    database: shopnoltd_db
