apiVersion: v1
kind: Service

metadata:
  name: oauth-service
  namespace: oauth


spec:

  selector:
    app: oauth-service


  ports:

  - name: http
    port: 80
    targetPort: 8001


  type: ClusterIP
