apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-service
  namespace: shopno-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: worker-service
