apiVersion: v1
kind: ConfigMap
metadata:
  name: social-service-config
  namespace: shopno-platform
data:
  ENV: "production"
  APP_NAME: "shopnoltd-social-service"
  APP_PORT: "8080"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  DATABASE_URL: "postgresql+asyncpg://shopno:shopno@postgres.shopno-data.svc.cluster.local:5432/social"
  REDIS_URL: "redis://redis.shopno-data.svc.cluster.local:6379/4"
  KEYCLOAK_ISSUER: "https://auth.shopnoltd.dpdns.org/realms/shopnoltd"
  KEYCLOAK_AUDIENCE: "social-service"
  STORAGE_SERVICE_URL: "http://storage-service.shopno-platform.svc.cluster.local:80"
  CORS_ORIGINS: "https://*.shopnoltd.dpdns.org"
