apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-service
  namespace: shopno-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: social.shopnoltd.dpdns.org,social-service.shopnoltd.dpdns.org
    external-dns.alpha.kubernetes.io/target: 5d6e037a-7c09-4788-8532-11dba5fc1a72.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - social.shopnoltd.dpdns.org
        - social-service.shopnoltd.dpdns.org
      secretName: social-service-tls
  rules:
    - host: social.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: social-service
                port:
                  number: 80
    - host: social-service.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: social-service
                port:
                  number: 80
