apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
  namespace: shopno-tools
data:
  GUACD_HOSTNAME: "guacd"
  GUACD_PORT: "4822"
  POSTGRESQL_HOSTNAME: "postgres.shopno-data.svc.cluster.local"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DATABASE: "guacamole"
  POSTGRESQL_USER: "guacamole_user"
