apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
  namespace: shopno-tools
data:
  GUACD_HOSTNAME: "guacd"
  GUACD_PORT: "4822"
  POSTGRES_HOSTNAME: "postgres.shopno-data.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "guacamole"
  POSTGRES_USER: "guacamole_user"
