apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
  namespace: default
  labels:
    app: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
      - name: mail-server
        image: docker.io/mailserver/docker-mailserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 587
          name: submission
        - containerPort: 993
          name: imaps
        env:
        - name: HOSTNAME
          value: mail
        - name: DOMAINNAME
          value: shopnoltd.dpdns.org
        - name: PERMIT_DOCKER
          value: network
        - name: ENABLE_FAIL2BAN
          value: "0"
        - name: ONE_DIR
          value: "1"
        volumeMounts:
        - name: mail-data
          mountPath: /var/mail
      volumes:
      - name: mail-data
        emptyDir: {}
