apiVersion: v1
kind: Service
metadata:
  name: mail-server
  namespace: shopno-mail
  labels:
    app: mail-server
spec:
  type: ClusterIP
  selector:
    app: mail-server
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    - name: smtps
      port: 465
      targetPort: smtps
      protocol: TCP
    - name: submission
      port: 587
      targetPort: submission
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: imaps
      protocol: TCP
