apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopno-apps

resources:
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- networkpolicy.yaml
- poddisruptionbudget.yaml
- servicemonitor.yaml

images:
- name: linuxserver/code-server
  newName: ghcr.io/asaduzzamanbheramara-prog/shopnoltd-code-server
  newTag: '"470a010229144b4a1df84bb80a7957995843a90a"'

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: code-server
- includeSelectors: false
  pairs:
    app.kubernetes.io/part-of: shopnoltd
