apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: code-server
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: code-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: code-server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
