apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: shopno-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
