apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: shopno-monitoring
  labels:
    app.kubernetes.io/name: loki
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
