apiVersion: v1
kind: Secret
metadata:
  name: ad-service-secret
  namespace: shopno-platform
type: Opaque
stringData:
  database-url: postgresql+asyncpg://shopno:REPLACE_ME@postgres.shopno-data.svc.cluster.local:5432/ads
