apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis
  namespace: shopno-data
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - redis.shopnoltd.com
      secretName: redis-tls
  rules:
    - host: redis.shopnoltd.com
      http:
        paths:
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: redis
                port:
                  number: 80
