apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# This component is a no-op when ServiceMonitor CRD is missing.
# When the prometheus-operator is installed, the SM resource becomes valid
# and is registered automatically.
resources:
- servicemonitor-conditional.yaml
