apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freedomain-service
  namespace: shopno-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - freedomain.shopnoltd.dpdns.org
      secretName: freedomain-service-tls
  rules:
    - host: freedomain.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freedomain-service
                port:
                  number: 80
