apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: freedomain-service
  namespace: shopno-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: freedomain-service
