apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: freedomain-service
  namespace: shopno-platform
  labels:
    app.kubernetes.io/name: freedomain-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: freedomain-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
