apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: shopno-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
