apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing-engine
  namespace: shopno-payments
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - billing-engine.shopnoltd.dpdns.org
      secretName: billing-engine-tls
  rules:
    - host: billing-engine.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: billing-engine
                port:
                  number: 80
