apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-engine
  namespace: shopno-payments
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: billing-engine
