apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-engine-data
  namespace: shopno-payments
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
