FROM postgis/postgis:16-3.4

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    clang-13 \
    postgresql-server-dev-16 \
    ca-certificates \
    && git clone --branch v0.7.4 https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/pgvector \
    && apt-get purge -y build-essential git clang-13 postgresql-server-dev-16 \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
