apiVersion: v1
kind: ConfigMap
metadata:
  name: live-service-config
data:
  ENV: production
  APP_NAME: shopnoltd-live-service
  OWNCAST_ADMIN_URL: https://live.shopnoltd.dpdns.org
  STORAGE_SERVICE_URL: http://storage-service.shopno-platform.svc.cluster.local:8080
  KEYCLOAK_ISSUER: https://auth.shopnoltd.dpdns.org/realms/shopnoltd
  KEYCLOAK_AUDIENCE: live-service
  CORS_ORIGINS: https://shopnoltd.dpdns.org
