apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: shopno-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
