apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metabase
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: metabase
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metabase
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
