apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiYjkxNTk0ZmQ1NjBjNThhMDljNDNmZGNiNzA3NTI5NzEiLCJUdW5uZWxTZWNyZXQiOiJNMkppWW1FeVl6Y3RaREJoT0MwME4yVmtMV0V6WWpZdE5tRXhOekpqWm1JNE56WTAiLCJUdW5uZWxJRCI6IjVkNmUwMzdhLTdjMDktNDc4OC04NTMyLTExZGJhNWZjMWE3MiIsIkVuZHBvaW50IjoiIn0=
kind: Secret
metadata:
  name: cloudflared-creds
  namespace: shopno-ingress
