apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  namespace: meet
  labels:
    app: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      containers:
      - name: jvb
        image: jitsi/jvb:stable
        env:
        - name: XMPP_AUTH_DOMAIN
          value: "auth.meet.jitsi"
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: "internal-muc.meet.jitsi"
        - name: XMPP_SERVER
          value: "prosody"
        - name: JVB_AUTH_USER
          value: "jvb"
        - name: JVB_AUTH_PASSWORD
          value: "ShopnoltdJvb2026"
        - name: JVB_BREWERY_MUC
          value: "jvbbrewery"
        - name: JVB_PORT
          value: "10000"
        - name: JVB_TCP_PORT
          value: "4443"
        - name: JVB_STUN_SERVERS
          value: "stun.l.google.com:19302"
        ports:
        - containerPort: 10000
          protocol: UDP
