apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-etc
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: gitea
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
