[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid

; =====================================================
; 🕸️ Nginx Process
; =====================================================
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/stdout.log
stderr_logfile=/var/log/nginx/stderr.log

; =====================================================
; 🐘 PHP-FPM Process
; =====================================================
[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm/stdout.log
stderr_logfile=/var/log/php-fpm/stderr.log
