[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
loglevel=info
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.err
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
redirect_stderr=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
redirect_stderr=true
