apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-portal
  namespace: shopno-platform
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - web-portal.shopnoltd.dpdns.org
        - shopnoltd.dpdns.org
      secretName: shopno-wildcard-tls

  rules:
    - host: web-portal.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-portal
                port:
                  number: 80

    - host: shopnoltd.dpdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: freedomain-service
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-portal
                port:
                  number: 80
