apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-portal-data
  namespace: shopno-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
