apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-infrastructure
  namespace: shopno-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin-infrastructure.shopnoltd.dpdns.org
      secretName: admin-infrastructure-tls
  rules:
    - host: admin-infrastructure.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-infrastructure
                port:
                  number: 8080
