apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-infrastructure
  namespace: shopno-platform
  labels:
    app.kubernetes.io/name: admin-infrastructure
    app.kubernetes.io/part-of: shopnoltd
