apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-service-read-kobotoolbox-mongo
  namespace: shopno-apps
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["kobotoolbox-mongo-auth"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-service-read-kobotoolbox-mongo
  namespace: shopno-apps
subjects:
  - kind: ServiceAccount
    name: api-service
    namespace: shopno-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-service-read-kobotoolbox-mongo
