apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: shopno-data
data:
  APP_NAME: "postgres"
  APP_PORT: "5432"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  ENV: "production"
  PATH_PREFIX: "/healthz"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4317"
  REDIS_HOST: "redis.data.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres.data.svc.cluster.local"
  POSTGRES_PORT: "5432"
  MINIO_ENDPOINT: "minio.data.svc.cluster.local:9000"
  KEYCLOAK_ISSUER: "https://auth.shopnoltd.dpdns.org/realms/shopnoltd"
  KEYCLOAK_CLIENT_ID: "postgres"
