"""
Central configuration for the Shopnoltd billing engine.

Every payment gateway is configured purely from environment variables
(populated in production via Kubernetes Secrets). Missing credentials never
mean that a real payment was processed.
"""

import os

from dotenv import load_dotenv

load_dotenv()


def _env(name: str, default: str = "") -> str:
    return os.getenv(name, default).strip()


DATABASE_URL = _env("DATABASE_URL", "sqlite:///./billing.db")
INTERNAL_API_KEY = _env("INTERNAL_API_KEY")

STRIPE_SECRET_KEY = _env("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = _env("STRIPE_WEBHOOK_SECRET")
STRIPE_ENABLED = bool(STRIPE_SECRET_KEY)

PAYPAL_CLIENT_ID = _env("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = _env("PAYPAL_CLIENT_SECRET")
PAYPAL_MODE = _env("PAYPAL_MODE", "sandbox")
PAYPAL_ENABLED = bool(PAYPAL_CLIENT_ID and PAYPAL_CLIENT_SECRET)

RAZORPAY_KEY_ID = _env("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = _env("RAZORPAY_KEY_SECRET")
RAZORPAY_ENABLED = bool(RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET)

SSLCOMMERZ_STORE_ID = _env("SSLCOMMERZ_STORE_ID")
SSLCOMMERZ_STORE_PASSWORD = _env("SSLCOMMERZ_STORE_PASSWORD")
SSLCOMMERZ_SANDBOX = _env("SSLCOMMERZ_SANDBOX", "true").lower() != "false"
SSLCOMMERZ_ENABLED = bool(SSLCOMMERZ_STORE_ID and SSLCOMMERZ_STORE_PASSWORD)

BKASH_APP_KEY = _env("BKASH_APP_KEY")
BKASH_APP_SECRET = _env("BKASH_APP_SECRET")
BKASH_USERNAME = _env("BKASH_USERNAME")
BKASH_PASSWORD = _env("BKASH_PASSWORD")
BKASH_SANDBOX = _env("BKASH_SANDBOX", "true").lower() != "false"
BKASH_ENABLED = bool(BKASH_APP_KEY and BKASH_APP_SECRET and BKASH_USERNAME and BKASH_PASSWORD)

NAGAD_MERCHANT_ID = _env("NAGAD_MERCHANT_ID")
NAGAD_MERCHANT_PRIVATE_KEY = _env("NAGAD_MERCHANT_PRIVATE_KEY")
NAGAD_PG_PUBLIC_KEY = _env("NAGAD_PG_PUBLIC_KEY")
NAGAD_SANDBOX = _env("NAGAD_SANDBOX", "true").lower() != "false"
NAGAD_ENABLED = bool(NAGAD_MERCHANT_ID and NAGAD_MERCHANT_PRIVATE_KEY and NAGAD_PG_PUBLIC_KEY)

MONEYBAG_API_KEY = _env("MONEYBAG_API_KEY")
MONEYBAG_WEBHOOK_SECRET = _env("MONEYBAG_WEBHOOK_SECRET")
MONEYBAG_MERCHANT_ID = _env("MONEYBAG_MERCHANT_ID")
MONEYBAG_MODE = _env("MONEYBAG_MODE", "sandbox")
MONEYBAG_SANDBOX = _env("MONEYBAG_SANDBOX", "true").lower() != "false"
MONEYBAG_WEBHOOK_TOLERANCE_SECONDS = int(_env("MONEYBAG_WEBHOOK_TOLERANCE_SECONDS", "300"))
MONEYBAG_ENABLED = bool(MONEYBAG_API_KEY)

NOWPAYMENTS_API_KEY = _env("NOWPAYMENTS_API_KEY")
NOWPAYMENTS_IPN_SECRET = _env("NOWPAYMENTS_IPN_SECRET")
NOWPAYMENTS_SANDBOX = _env("NOWPAYMENTS_SANDBOX", "true").lower() != "false"
CRYPTO_ENABLED = bool(NOWPAYMENTS_API_KEY)

PAYONEER_PROGRAM_ID = _env("PAYONEER_PROGRAM_ID")
PAYONEER_API_USERNAME = _env("PAYONEER_API_USERNAME")
PAYONEER_API_PASSWORD = _env("PAYONEER_API_PASSWORD")
PAYONEER_SANDBOX = _env("PAYONEER_SANDBOX", "true").lower() != "false"
PAYONEER_ENABLED = bool(PAYONEER_PROGRAM_ID and PAYONEER_API_USERNAME and PAYONEER_API_PASSWORD)

EXCHANGE_RATE_API_KEY = _env("EXCHANGE_RATE_API_KEY")
EXCHANGE_RATE_LIVE_ENABLED = bool(EXCHANGE_RATE_API_KEY)
EXCHANGE_RATE_CACHE_SECONDS = int(_env("EXCHANGE_RATE_CACHE_SECONDS", "3600"))

BASE_CALLBACK_URL = _env("BASE_CALLBACK_URL", "https://billing.shopnoltd.dpdns.org")

GATEWAY_STATUS = {
    "stripe": STRIPE_ENABLED,
    "paypal": PAYPAL_ENABLED,
    "razorpay": RAZORPAY_ENABLED,
    "sslcommerz": SSLCOMMERZ_ENABLED,
    "bkash": BKASH_ENABLED,
    "nagad": NAGAD_ENABLED,
    "moneybag": MONEYBAG_ENABLED,
    "crypto": CRYPTO_ENABLED,
}
