apiVersion: v1
kind: Service
metadata:
  name: owncast
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: owncast
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: owncast
