apiVersion: v1
kind: Secret
metadata:
  name: shopnoltd-secrets
  namespace: default
type: Opaque
data:
  # These are base64 encoded values - replace with your actual base64 encoded secrets
  TURNSTILE_SECRET_KEY: "MHg0QUFBQUFBRGxKdVRHbHBRaXExRVpSUSM="
  RECAPTCHA_SECRET_KEY: "NkxjVld5QXRUQUFBQUFGb3JOR1d0RU01c2kxYWl5Wl9nVDdnZC1XSlkj"
  GITHUB_CLIENT_SECRET: "NjgyYWM2YTYzMzJmODVlZGEyNzExM2FkNmU2MzRmNTFlZmYwZmZlMiM="
  GOOGLE_CLIENT_SECRET: "R09DU1BYLUVjbXV5d2xPVkN2U2xENnhDNGY0c1JqTXVKTkoj"
