# Shopnoltd WSL/k3s automatic startup helper for the Windows host.
#
# This installer intentionally runs in the current interactive user's security
# context. The verified Shopnoltd setup uses the Windows user logon to start
# WSL and keeps the distro alive with a long-running foreground process.
# WSL systemd then starts enabled services such as k3s and the GitHub Actions
# runner service.
#
# No passwords, Kubernetes credentials, GitHub tokens, database credentials,
# or other secrets are stored or generated by this script.

[CmdletBinding()]
param(
    [string]$Distro = 'Ubuntu'
)

$ErrorActionPreference = 'Stop'

$TaskName = 'Shopnoltd-WSL-Autostart'
$WslPath = Join-Path $env:SystemRoot 'System32\wsl.exe'

if (-not (Test-Path -LiteralPath $WslPath)) {
    throw "wsl.exe not found at $WslPath"
}

if ([string]::IsNullOrWhiteSpace($env:USERNAME)) {
    throw 'The current Windows username could not be determined.'
}

# The foreground sleep is intentional. WSL may terminate when no foreground
# process remains. The verified production task uses this exact pattern:
#   wsl.exe -d Ubuntu --exec sleep infinity
#
# Do not replace this with /bin/true: that process exits immediately and does
# not reliably keep the WSL instance alive for the Shopnoltd server.
$Action = New-ScheduledTaskAction `
    -Execute $WslPath `
    -Argument "-d `"$Distro`" --exec sleep infinity"

# Start after the configured Windows user logs on. Shopnoltd uses Windows
# Autologon, so this runs automatically after a normal reboot.
$Trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

# InteractiveToken matches the verified task: RunAs the logged-in user rather
# than SYSTEM. Limited is sufficient because wsl.exe does not require an
# elevated task. This also avoids creating a separate SYSTEM WSL context.
$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType InteractiveToken `
    -RunLevel Limited

# Do not set an execution time limit: sleep infinity is the process that keeps
# WSL alive continuously while Windows remains running.
$Settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $Action `
    -Trigger $Trigger `
    -Principal $Principal `
    -Settings $Settings `
    -Force | Out-Null

Write-Host "Installed $TaskName for WSL distro: $Distro" -ForegroundColor Green
Write-Host "RunAs user: $env:USERNAME" -ForegroundColor Green
Write-Host 'Startup chain: Windows logon -> WSL -> systemd -> k3s -> ArgoCD -> Shopnoltd services.' -ForegroundColor Green
Write-Host 'The GitHub Actions runner must already be installed as a system service inside WSL.' -ForegroundColor Yellow
Write-Host 'Keep Windows Sleep and Hibernate disabled for 24/7 hosting; display-off is safe.' -ForegroundColor Yellow
