apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meshcentral
  namespace: shopno-tools
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - remote.shopnoltd.dpdns.org
        - remote-engine.shopnoltd.dpdns.org
      secretName: shopno-wildcard-tls

  rules:
    - host: remote.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meshcentral
                port:
                  number: 443

    - host: remote-engine.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meshcentral
                port:
                  number: 443
