apiVersion: v1
kind: Service
metadata:
  name: remote-device-gateway
  namespace: shopno-tools
spec:
  selector:
    app.kubernetes.io/name: remote-device-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
