apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-device-ui
  namespace: shopno-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-device-ui
  template:
    metadata:
      labels:
        app: remote-device-ui
    spec:
      containers:
        - name: nginx
          image: nginx:1.29-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: html
          configMap:
            name: remote-device-ui
