apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-service-config
data:
  ENV: production
  APP_NAME: shopnoltd-messaging-service
  KEYCLOAK_ISSUER: https://auth.shopnoltd.dpdns.org/realms/shopnoltd
  KEYCLOAK_AUDIENCE: messaging-service
  CORS_ORIGINS: https://shopnoltd.dpdns.org
