apiVersion: v1
kind: Secret
metadata:
  name: messaging-service-secret
  namespace: shopno-platform
stringData:
  DATABASE_URL: postgresql+asyncpg://shopno:REPLACE_ME@postgres.shopno-data.svc.cluster.local:5432/messaging
  REDIS_URL: redis://redis.shopno-data.svc.cluster.local:6379/0
