apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jitsi-web
  namespace: shopno-apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jitsi-web.shopnoltd.dpdns.org
      secretName: jitsi-web-tls
  rules:
    - host: jitsi-web.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jitsi-web
                port:
                  number: 80
