apiVersion: v1
kind: Service
metadata:
  name: enketo
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: enketo
    app.kubernetes.io/part-of: shopnoltd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: enketo
  ports:
    - name: http
      port: 8005
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enketo
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: enketo
    app.kubernetes.io/part-of: shopnoltd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: enketo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enketo
        app.kubernetes.io/part-of: shopnoltd
    spec:
      containers:
        - name: enketo
          image: docker.io/kobotoolbox/enketo-express-extra-widgets:2.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8005
          env:
            - name: ENKETO_URL
              value: "https://enketo.shopnoltd.dpdns.org"
            - name: ENKETO_API_URL
              value: "https://kobo.shopnoltd.dpdns.org"
            - name: ENKETO_REDIS_HOST
              value: "redis.shopno-data.svc.cluster.local"
            - name: ENKETO_REDIS_PORT
              value: "6379"
            - name: ENKETO_REDIS_DB
              value: "5"
            - name: ENKETO_POSTGRES_HOST
              value: "postgres.shopno-data.svc.cluster.local"
            - name: ENKETO_POSTGRES_PORT
              value: "5432"
            - name: ENKETO_POSTGRES_USER
              value: "postgres"
            - name: ENKETO_POSTGRES_PASSWORD
              value: "5XuByzqhn6nJyq7iR7xva58iKHLSUSj"
            - name: ENKETO_POSTGRES_DB
              value: "enketo"
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "1Gi" }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enketo
  namespace: shopno-apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enketo
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {}
        - podSelector: {}
      ports:
        - port: 8005
          protocol: TCP
  egress:
    - {}
