apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service
  namespace: shopno-identity
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
