# Generated Kubernetes secrets YAML (sensitive)
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
type: Opaque
data:
  JWT_SECRET: NTI2YTRjMzctYjdhZi00N2E4LTgwNTYtZGY0NjU1NGY4OTQ5
  SESSION_SECRET: NTQzZDEyMjktYWI4YS00M2M1LWI5YjMtNmU0NjM3MTg2YzBh
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: c2hvcG5vbHRk
  POSTGRES_PASSWORD: Mzg1YTFhNDQtNTdiYy00MjcwLTljNmQtZGQyMWRhNGVjZGFh
  POSTGRES_USER: c2hvcG5vbHRk
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVRqaHdYMldsMUM3c05FNHB6bHk3OFBUYWo5UTJrTmk2SjhCREFJSDZ1N2dIbEppMHJLUXlnUVd1OXExbmVOM3VhSFpwblVZN2QybmFPU2lieFVSbE1NTzAwSFBYQzEzbEI=
  STRIPE_WEBHOOK_SECRET: d2hzZWNfcnlhZjUxTkM1WTFnUWRCdm5wSFZtdnFMbkZxQVVKVWg=
  STRIPE_PRICE_BASIC: cHJpY2VfMVRqalJuMldsMUM3c05FNFNiSWdkTUpF
  STRIPE_PRICE_PRO: cHJpY2VfMVRqalN2MldsMUM3c05FNExRQUkzSEFk
  STRIPE_PRICE_ENTERPRISE: cHJpY2VfMVRqalRiMldsMUM3c05FNFJrTlhQZDc2
  BILLING_API_KEY: d2VfMVRqanZ3MldsMUM3c05FNFMwQlZNcWxp
  FRONTEND_URL: aHR0cHM6Ly9zaG9wbm9sdGQuZHBkbnMub3Jn
  POSTGRES_URL: cG9zdGdyZXM6Ly9zaG9wbm9sdGQ6Mzg1YTFhNDQtNTdiYy00MjcwLTljNmQtZGQyMWRhNGVjZGFhQHBvc3RncmVzOjU0MzIvc2hvcG5vbHRk
