#!/usr/bin/env python3
"""
Generate missing k8s/services/*/secret.yaml files.

Every service's kustomization.yaml lists `secret.yaml` as a resource, but the
file itself was never committed (it matches the repo's .gitignore secret
patterns). That means `kubectl apply -k k8s/services/<name>` / `kustomize
build` fails for every single service with a missing-resource error.

This script inspects each deployment.yaml to find:
  - envFrom: secretRef: name: <secret-name>   -> whole-secret references
  - env: valueFrom: secretKeyRef: {name, key}  -> individual key references

...and emits a `secret.yaml` template (placeholder values only, never real
secrets) for each referenced Secret object, grouped by service directory.
"""
import os
import sys
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SERVICES_DIR = os.path.join(ROOT, "k8s", "services")


def load_docs(path):
    with open(path) as f:
        return list(yaml.safe_load_all(f))


def find_secret_refs(deployment_docs):
    """Return {secret_name: set(keys)} referenced by this deployment.
    An empty set means 'whole secret via envFrom' (all keys unknown)."""
    refs = {}
    for doc in deployment_docs:
        if not doc or doc.get("kind") != "Deployment":
            continue
        containers = (
            doc.get("spec", {})
            .get("template", {})
            .get("spec", {})
            .get("containers", [])
        )
        for c in containers:
            for ef in c.get("envFrom", []) or []:
                name = ef.get("secretRef", {}).get("name")
                if name:
                    refs.setdefault(name, set())
            for e in c.get("env", []) or []:
                skr = (e.get("valueFrom") or {}).get("secretKeyRef")
                if skr and skr.get("name"):
                    refs.setdefault(skr["name"], set())
                    if skr.get("key"):
                        refs[skr["name"]].add(skr["key"])
    return refs


def render_secret_yaml(namespace, secrets):
    docs = []
    for name, keys in sorted(secrets.items()):
        data = {k: "REPLACE_WITH_BASE64" for k in sorted(keys)} or {
            "REPLACE_ME": "REPLACE_WITH_BASE64"
        }
        doc = {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {"name": name, "namespace": namespace},
            "type": "Opaque",
            "data": data,
        }
        docs.append(doc)
    header = (
        "# AUTO-GENERATED TEMPLATE -- placeholders only, no real secrets.\n"
        "# Fill in base64-encoded values (or apply via sealed-secrets /\n"
        "# external-secrets) before `kubectl apply -k` in this directory.\n"
        "# Generated by scripts/generate_missing_secrets.py\n"
    )
    return header + yaml.safe_dump_all(docs, sort_keys=False)


def main():
    created, skipped, no_refs = [], [], []
    for svc in sorted(os.listdir(SERVICES_DIR)):
        svc_dir = os.path.join(SERVICES_DIR, svc)
        kustom = os.path.join(svc_dir, "kustomization.yaml")
        deploy = os.path.join(svc_dir, "deployment.yaml")
        secret_path = os.path.join(svc_dir, "secret.yaml")
        if not os.path.isfile(kustom):
            continue
        with open(kustom) as f:
            k = yaml.safe_load(f) or {}
        if "secret.yaml" not in (k.get("resources") or []):
            continue
        if os.path.isfile(secret_path):
            skipped.append(svc)
            continue
        if not os.path.isfile(deploy):
            no_refs.append(svc)
            continue
        namespace = k.get("namespace", "default")
        refs = find_secret_refs(load_docs(deploy))
        if not refs:
            no_refs.append(svc)
            continue
        with open(secret_path, "w") as f:
            f.write(render_secret_yaml(namespace, refs))
        created.append((svc, list(refs.keys())))

    print(f"Created {len(created)} secret.yaml files:")
    for svc, names in created:
        print(f"  {svc}: {', '.join(names)}")
    if no_refs:
        print(f"\nNo secretRef found in deployment.yaml (skipped, needs manual check): {no_refs}")
    if skipped:
        print(f"\nAlready had secret.yaml (left untouched): {skipped}")


if __name__ == "__main__":
    main()
