apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-server-core-pod-access
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server-core-pod-access
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-server-core-pod-access
