apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: android-cloud-web
  namespace: shopno-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - android.shopnoltd.dpdns.org
      secretName: shopno-wildcard-tls
  rules:
    - host: android.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: android-cloud-web
                port:
                  number: 8080
