apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: android-cloud-controller
  namespace: shopno-android
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: android-cloud-controller
  namespace: shopno-android
subjects:
  - kind: User
    name: system:serviceaccount:shopno-platform:android-cloud-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: android-cloud-controller
