apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-service-data
  namespace: shopno-payments
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
