apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
  namespace: shopno-apps
  labels:
    app.kubernetes.io/name: onlyoffice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: onlyoffice
