apiVersion: v1
kind: Service
metadata:
  name: ai-platform
  namespace: shopno-platform
  labels:
    app.kubernetes.io/name: ai-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ai-platform
