apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus
  namespace: shopno-monitoring
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
