apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopno-apps

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: superset
  app.kubernetes.io/part-of: shopnoltd

