apiVersion: v1
data:
  default.conf: |
    server {
        listen 80;
        location / {
            include uwsgi_params;
            uwsgi_pass 127.0.0.1:8000;
            uwsgi_read_timeout 300;
            uwsgi_send_timeout 300;
            client_max_body_size 100m;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default.conf":"server {\n    listen 80;\n    location / {\n        include uwsgi_params;\n        uwsgi_pass 127.0.0.1:8000;\n        uwsgi_read_timeout 300;\n        uwsgi_send_timeout 300;\n        client_max_body_size 100m;\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kf-nginx-conf","namespace":"toolbox"}}
  creationTimestamp: "2026-06-30T16:18:19Z"
  name: kf-nginx-conf
  namespace: toolbox
  resourceVersion: "301454"
  uid: 0ac05ed9-332f-43f4-82f2-2f3e8bb2be34
