#!/usr/bin/env bash
set -euo pipefail

# Run this script on the trusted k3s node as the dedicated GitHub Actions
# runner account. It never stores a registration token in Git.
#
# Required environment:
#   RUNNER_TOKEN  - short-lived token generated by GitHub repository Settings
#                   -> Actions -> Runners -> New self-hosted runner
# Optional:
#   RUNNER_VERSION - exact runner release, e.g. 2.329.0
#   RUNNER_DIR     - installation directory (default: ~/actions-runner)
#   REPO_URL      - repository URL (default: this repository)

REPO_URL="${REPO_URL:-https://github.com/asaduzzamanbheramara-prog/shopnoltd}"
RUNNER_DIR="${RUNNER_DIR:-$HOME/actions-runner}"

if [[ -z "${RUNNER_TOKEN:-}" ]]; then
  echo "ERROR: RUNNER_TOKEN is required but is intentionally not stored in Git."
  exit 1
fi

command -v curl >/dev/null || { echo 'ERROR: curl is required'; exit 1; }
command -v tar >/dev/null || { echo 'ERROR: tar is required'; exit 1; }
command -v kubectl >/dev/null || { echo 'ERROR: kubectl is required'; exit 1; }

mkdir -p "$RUNNER_DIR"
cd "$RUNNER_DIR"

if [[ -z "${RUNNER_VERSION:-}" ]]; then
  RUNNER_VERSION="$(curl -fsSL https://api.github.com/repos/actions/runner/releases/latest \
    | sed -n 's/.*"tag_name": "v\([^"]*\)".*/\1/p' | head -1)"
fi

if [[ -z "$RUNNER_VERSION" ]]; then
  echo "ERROR: could not determine GitHub Actions runner version"
  exit 1
fi

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64) PACKAGE_ARCH=x64 ;;
  aarch64|arm64) PACKAGE_ARCH=arm64 ;;
  *) echo "ERROR: unsupported architecture: $ARCH"; exit 1 ;;
esac

PACKAGE="actions-runner-linux-${PACKAGE_ARCH}-${RUNNER_VERSION}.tar.gz"
URL="https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/${PACKAGE}"

if [[ ! -f .runner ]]; then
  curl -fL --retry 3 -o "$PACKAGE" "$URL"
  tar xzf "$PACKAGE"
  rm -f "$PACKAGE"

  ./config.sh \
    --url "$REPO_URL" \
    --token "$RUNNER_TOKEN" \
    --name "shopnoltd-k3s-$(hostname -s)" \
    --labels "self-hosted,linux,shopnoltd,k3s" \
    --work "_work" \
    --unattended \
    --replace
else
  echo "Runner already configured in $RUNNER_DIR"
fi

unset RUNNER_TOKEN

# GitHub's supported service wrapper keeps the runner available after reboot.
sudo ./svc.sh install "$(id -un)"
sudo ./svc.sh start
sudo ./svc.sh status

echo
echo "Runner installed and started."
echo "KUBECONFIG must be available to the runner account; do not commit it to Git."
echo "Recommended: grant this dedicated runner only the minimum Kubernetes RBAC required by the deployment workflow."
