apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"kf","namespace":"toolbox"},"spec":{"ports":[{"port":80}],"selector":{"app":"kf"}}}
  creationTimestamp: "2026-06-26T18:08:38Z"
  name: kf
  namespace: toolbox
  resourceVersion: "301610"
  uid: 7f943507-e07a-493d-949f-65c02efde80d
spec:
  clusterIP: 10.96.150.49
  clusterIPs:
  - 10.96.150.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kf
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
