apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: shopno-identity
data:
  APP_NAME: "keycloak"
  APP_PORT: "8080"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  ENV: "production"
  PATH_PREFIX: "/"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4317"
  REDIS_HOST: "redis.shopno-data.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres.shopno-data.svc.cluster.local"
  POSTGRES_PORT: "5432"
  MINIO_ENDPOINT: "minio.shopno-data.svc.cluster.local:9000"
  KEYCLOAK_ISSUER: "https://auth.shopnoltd.dpdns.org/realms/shopnoltd"
  KEYCLOAK_CLIENT_ID: "keycloak"
  KC_DB: postgres
  KC_DB_URL_HOST: postgres.shopno-data.svc.cluster.local
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: keycloak
  KC_DB_USERNAME: keycloak
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_PROXY_HEADERS: xforwarded
  KC_HOSTNAME: auth.shopnoltd.dpdns.org
  KC_HOSTNAME_STRICT: "false"
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
