apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-portal-data
  namespace: shopno-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
