apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-service
  namespace: shopno-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api-service.shopnoltd.dpdns.org
      secretName: api-service-tls
  rules:
    - host: api-service.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
