apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-service
  namespace: shopno-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - api.shopnoltd.dpdns.org
      secretName: api-service-tls

  rules:
    - host: api.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
