apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pc-portal
  namespace: shopno-platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shopnoltdpc.shopnoltd.dpdns.org
      secretName: pc-portal-tls
  rules:
    - host: shopnoltdpc.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pc-portal
                port:
                  number: 80
