apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- session-manager-deployment.yaml
- pvc.yaml
- session-manager-service.yaml
- session-manager-ingress.yaml
- session-manager-vnc-ingress.yaml
