apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-manager-data
  namespace: shopno-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
