apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: session-manager-allow-ingress
  namespace: shopno-tools
spec:
  podSelector:
    matchLabels:
      app: session-manager

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 6080

    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 6080
