apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enketo
  namespace: shopno-apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - enketo.shopnoltd.dpdns.org
      secretName: enketo-tls
  rules:
    - host: enketo.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enketo
                port:
                  number: 8005
