apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enketo
  namespace: shopno-apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enketo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
        - podSelector: {}
      ports:
        - port: 8005
          protocol: TCP
  egress:
    - {}
