apiVersion: v1
kind: Service
metadata:
  name: enketo
  namespace: shopno-apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: enketo
  ports:
    - name: http
      port: 8005
      targetPort: http
