apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: shopno-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
