apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-service
  namespace: shopno-mail
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.mail.shopnoltd.dpdns.org
      secretName: mail-service-tls
  rules:
    - host: api.mail.shopnoltd.dpdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mail-service
                port:
                  number: 80
