apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  namespace: shopno-monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
