apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopno-monitoring

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
  - loki-config.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - grafana-datasources.yaml
  - grafana-dashboards.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: shopnoltd-observability
