apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  namespace: shopno-monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data
  namespace: shopno-monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: shopno-monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: shopnoltd-local-immediate
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: shopno-monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: shopnoltd-local-immediate
  resources:
    requests:
      storage: 10Gi
